//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WearDropWA.FaldaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", ConfigurationName="FaldaWS.FaldaWS")]
    public interface FaldaWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/obtenerFaldaPorIdRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/obtenerFaldaPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(prenda))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.FaldaWS.obtenerFaldaPorIdResponse obtenerFaldaPorId(WearDropWA.FaldaWS.obtenerFaldaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/obtenerFaldaPorIdRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/obtenerFaldaPorIdResponse")]
        System.Threading.Tasks.Task<WearDropWA.FaldaWS.obtenerFaldaPorIdResponse> obtenerFaldaPorIdAsync(WearDropWA.FaldaWS.obtenerFaldaPorIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/listarFaldasRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/listarFaldasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(prenda))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.FaldaWS.listarFaldasResponse listarFaldas(WearDropWA.FaldaWS.listarFaldasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/listarFaldasRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/listarFaldasResponse")]
        System.Threading.Tasks.Task<WearDropWA.FaldaWS.listarFaldasResponse> listarFaldasAsync(WearDropWA.FaldaWS.listarFaldasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/eliminarFaldaRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/eliminarFaldaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(prenda))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.FaldaWS.eliminarFaldaResponse eliminarFalda(WearDropWA.FaldaWS.eliminarFaldaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/eliminarFaldaRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/eliminarFaldaResponse")]
        System.Threading.Tasks.Task<WearDropWA.FaldaWS.eliminarFaldaResponse> eliminarFaldaAsync(WearDropWA.FaldaWS.eliminarFaldaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/filtrarFaldasRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/filtrarFaldasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(prenda))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.FaldaWS.filtrarFaldasResponse filtrarFaldas(WearDropWA.FaldaWS.filtrarFaldasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/filtrarFaldasRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/filtrarFaldasResponse")]
        System.Threading.Tasks.Task<WearDropWA.FaldaWS.filtrarFaldasResponse> filtrarFaldasAsync(WearDropWA.FaldaWS.filtrarFaldasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/insertarFaldaRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/insertarFaldaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(prenda))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.FaldaWS.insertarFaldaResponse insertarFalda(WearDropWA.FaldaWS.insertarFaldaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/insertarFaldaRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/insertarFaldaResponse")]
        System.Threading.Tasks.Task<WearDropWA.FaldaWS.insertarFaldaResponse> insertarFaldaAsync(WearDropWA.FaldaWS.insertarFaldaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/modificarFaldaRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/modificarFaldaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(prenda))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.FaldaWS.modificarFaldaResponse modificarFalda(WearDropWA.FaldaWS.modificarFaldaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/modificarFaldaRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/FaldaWS/modificarFaldaResponse")]
        System.Threading.Tasks.Task<WearDropWA.FaldaWS.modificarFaldaResponse> modificarFaldaAsync(WearDropWA.FaldaWS.modificarFaldaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public partial class falda : prenda {
        
        private bool conForroField;
        
        private bool conVolantesField;
        
        private double largoField;
        
        private tipoFalda tipoFaldaField;
        
        private bool tipoFaldaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool conForro {
            get {
                return this.conForroField;
            }
            set {
                this.conForroField = value;
                this.RaisePropertyChanged("conForro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool conVolantes {
            get {
                return this.conVolantesField;
            }
            set {
                this.conVolantesField = value;
                this.RaisePropertyChanged("conVolantes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double largo {
            get {
                return this.largoField;
            }
            set {
                this.largoField = value;
                this.RaisePropertyChanged("largo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public tipoFalda tipoFalda {
            get {
                return this.tipoFaldaField;
            }
            set {
                this.tipoFaldaField = value;
                this.RaisePropertyChanged("tipoFalda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoFaldaSpecified {
            get {
                return this.tipoFaldaFieldSpecified;
            }
            set {
                this.tipoFaldaFieldSpecified = value;
                this.RaisePropertyChanged("tipoFaldaSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public enum tipoFalda {
        
        /// <remarks/>
        Mini,
        
        /// <remarks/>
        Midi,
        
        /// <remarks/>
        Larga,
        
        /// <remarks/>
        Tubo,
        
        /// <remarks/>
        Plisada,
        
        /// <remarks/>
        Cruzada,
        
        /// <remarks/>
        ShortFalda,
        
        /// <remarks/>
        Otro,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(falda))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public abstract partial class prenda : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int alertaMinStockField;
        
        private string colorField;
        
        private descuento[] descuentosField;
        
        private int idPrendaField;
        
        private lote[] lotesField;
        
        private material materialField;
        
        private bool materialFieldSpecified;
        
        private string nombreField;
        
        private double precioDocenaField;
        
        private double precioMayorField;
        
        private double precioUnidadField;
        
        private promocion[] promocionesField;
        
        private int stockPrendaField;
        
        private System.Nullable<talla>[] tallaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int alertaMinStock {
            get {
                return this.alertaMinStockField;
            }
            set {
                this.alertaMinStockField = value;
                this.RaisePropertyChanged("alertaMinStock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("color");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("descuentos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public descuento[] descuentos {
            get {
                return this.descuentosField;
            }
            set {
                this.descuentosField = value;
                this.RaisePropertyChanged("descuentos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idPrenda {
            get {
                return this.idPrendaField;
            }
            set {
                this.idPrendaField = value;
                this.RaisePropertyChanged("idPrenda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lotes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public lote[] lotes {
            get {
                return this.lotesField;
            }
            set {
                this.lotesField = value;
                this.RaisePropertyChanged("lotes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public material material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
                this.RaisePropertyChanged("material");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool materialSpecified {
            get {
                return this.materialFieldSpecified;
            }
            set {
                this.materialFieldSpecified = value;
                this.RaisePropertyChanged("materialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double precioDocena {
            get {
                return this.precioDocenaField;
            }
            set {
                this.precioDocenaField = value;
                this.RaisePropertyChanged("precioDocena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double precioMayor {
            get {
                return this.precioMayorField;
            }
            set {
                this.precioMayorField = value;
                this.RaisePropertyChanged("precioMayor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double precioUnidad {
            get {
                return this.precioUnidadField;
            }
            set {
                this.precioUnidadField = value;
                this.RaisePropertyChanged("precioUnidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("promociones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public promocion[] promociones {
            get {
                return this.promocionesField;
            }
            set {
                this.promocionesField = value;
                this.RaisePropertyChanged("promociones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int stockPrenda {
            get {
                return this.stockPrendaField;
            }
            set {
                this.stockPrendaField = value;
                this.RaisePropertyChanged("stockPrenda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("talla", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public System.Nullable<talla>[] talla {
            get {
                return this.tallaField;
            }
            set {
                this.tallaField = value;
                this.RaisePropertyChanged("talla");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public abstract partial class descuento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool esAutomaticoField;
        
        private int idDescuentoField;
        
        private string nombreField;
        
        private vigencia vigenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool esAutomatico {
            get {
                return this.esAutomaticoField;
            }
            set {
                this.esAutomaticoField = value;
                this.RaisePropertyChanged("esAutomatico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idDescuento {
            get {
                return this.idDescuentoField;
            }
            set {
                this.idDescuentoField = value;
                this.RaisePropertyChanged("idDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public vigencia vigencia {
            get {
                return this.vigenciaField;
            }
            set {
                this.vigenciaField = value;
                this.RaisePropertyChanged("vigencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public partial class vigencia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idVigenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idVigencia {
            get {
                return this.idVigenciaField;
            }
            set {
                this.idVigenciaField = value;
                this.RaisePropertyChanged("idVigencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public abstract partial class promocion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool esAutomaticoField;
        
        private int idPromocionField;
        
        private string nombreField;
        
        private vigencia vigenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool esAutomatico {
            get {
                return this.esAutomaticoField;
            }
            set {
                this.esAutomaticoField = value;
                this.RaisePropertyChanged("esAutomatico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idPromocion {
            get {
                return this.idPromocionField;
            }
            set {
                this.idPromocionField = value;
                this.RaisePropertyChanged("idPromocion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public vigencia vigencia {
            get {
                return this.vigenciaField;
            }
            set {
                this.vigenciaField = value;
                this.RaisePropertyChanged("vigencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public partial class almacen : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idField;
        
        private int idTiendaField;
        
        private string nombreField;
        
        private int stockField;
        
        private string ubicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idTienda {
            get {
                return this.idTiendaField;
            }
            set {
                this.idTiendaField = value;
                this.RaisePropertyChanged("idTienda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public partial class lote : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private almacen datAlmacenField;
        
        private string descripcionField;
        
        private int idLoteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public almacen datAlmacen {
            get {
                return this.datAlmacenField;
            }
            set {
                this.datAlmacenField = value;
                this.RaisePropertyChanged("datAlmacen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idLote {
            get {
                return this.idLoteField;
            }
            set {
                this.idLoteField = value;
                this.RaisePropertyChanged("idLote");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public enum material {
        
        /// <remarks/>
        Algodon,
        
        /// <remarks/>
        Poliester,
        
        /// <remarks/>
        algodon_poliester,
        
        /// <remarks/>
        Lino,
        
        /// <remarks/>
        Rayon,
        
        /// <remarks/>
        Lana,
        
        /// <remarks/>
        Acrilico,
        
        /// <remarks/>
        Nylon,
        
        /// <remarks/>
        lycra,
        
        /// <remarks/>
        Denim,
        
        /// <remarks/>
        Drill,
        
        /// <remarks/>
        Gabardina,
        
        /// <remarks/>
        Polar,
        
        /// <remarks/>
        Franela,
        
        /// <remarks/>
        Cuero,
        
        /// <remarks/>
        Cuerina,
        
        /// <remarks/>
        Saten,
        
        /// <remarks/>
        Chifon,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public enum talla {
        
        /// <remarks/>
        XS,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        XL,
        
        /// <remarks/>
        XXL,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerFaldaPorId", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerFaldaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idFalda;
        
        public obtenerFaldaPorIdRequest() {
        }
        
        public obtenerFaldaPorIdRequest(int idFalda) {
            this.idFalda = idFalda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerFaldaPorIdResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerFaldaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.FaldaWS.falda @return;
        
        public obtenerFaldaPorIdResponse() {
        }
        
        public obtenerFaldaPorIdResponse(WearDropWA.FaldaWS.falda @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarFaldas", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarFaldasRequest {
        
        public listarFaldasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarFaldasResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarFaldasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.FaldaWS.falda[] @return;
        
        public listarFaldasResponse() {
        }
        
        public listarFaldasResponse(WearDropWA.FaldaWS.falda[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarFalda", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarFaldaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idFalda;
        
        public eliminarFaldaRequest() {
        }
        
        public eliminarFaldaRequest(int idFalda) {
            this.idFalda = idFalda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarFaldaResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarFaldaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarFaldaResponse() {
        }
        
        public eliminarFaldaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="filtrarFaldas", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class filtrarFaldasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreLike;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string colorLike;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string materialLike;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoFaldaLike;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool conForro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool conVolantes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double precioMin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double precioMax;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double largoMin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double largoMax;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool soloActivos;
        
        public filtrarFaldasRequest() {
        }
        
        public filtrarFaldasRequest(string nombreLike, string colorLike, string materialLike, string tipoFaldaLike, bool conForro, bool conVolantes, double precioMin, double precioMax, double largoMin, double largoMax, bool soloActivos) {
            this.nombreLike = nombreLike;
            this.colorLike = colorLike;
            this.materialLike = materialLike;
            this.tipoFaldaLike = tipoFaldaLike;
            this.conForro = conForro;
            this.conVolantes = conVolantes;
            this.precioMin = precioMin;
            this.precioMax = precioMax;
            this.largoMin = largoMin;
            this.largoMax = largoMax;
            this.soloActivos = soloActivos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="filtrarFaldasResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class filtrarFaldasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.FaldaWS.falda[] @return;
        
        public filtrarFaldasResponse() {
        }
        
        public filtrarFaldasResponse(WearDropWA.FaldaWS.falda[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarFalda", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarFaldaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.FaldaWS.falda falda;
        
        public insertarFaldaRequest() {
        }
        
        public insertarFaldaRequest(WearDropWA.FaldaWS.falda falda) {
            this.falda = falda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarFaldaResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarFaldaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarFaldaResponse() {
        }
        
        public insertarFaldaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarFalda", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarFaldaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.FaldaWS.falda falda;
        
        public modificarFaldaRequest() {
        }
        
        public modificarFaldaRequest(WearDropWA.FaldaWS.falda falda) {
            this.falda = falda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarFaldaResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarFaldaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarFaldaResponse() {
        }
        
        public modificarFaldaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FaldaWSChannel : WearDropWA.FaldaWS.FaldaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FaldaWSClient : System.ServiceModel.ClientBase<WearDropWA.FaldaWS.FaldaWS>, WearDropWA.FaldaWS.FaldaWS {
        
        public FaldaWSClient() {
        }
        
        public FaldaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FaldaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FaldaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FaldaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.FaldaWS.obtenerFaldaPorIdResponse WearDropWA.FaldaWS.FaldaWS.obtenerFaldaPorId(WearDropWA.FaldaWS.obtenerFaldaPorIdRequest request) {
            return base.Channel.obtenerFaldaPorId(request);
        }
        
        public WearDropWA.FaldaWS.falda obtenerFaldaPorId(int idFalda) {
            WearDropWA.FaldaWS.obtenerFaldaPorIdRequest inValue = new WearDropWA.FaldaWS.obtenerFaldaPorIdRequest();
            inValue.idFalda = idFalda;
            WearDropWA.FaldaWS.obtenerFaldaPorIdResponse retVal = ((WearDropWA.FaldaWS.FaldaWS)(this)).obtenerFaldaPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.FaldaWS.obtenerFaldaPorIdResponse> WearDropWA.FaldaWS.FaldaWS.obtenerFaldaPorIdAsync(WearDropWA.FaldaWS.obtenerFaldaPorIdRequest request) {
            return base.Channel.obtenerFaldaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.FaldaWS.obtenerFaldaPorIdResponse> obtenerFaldaPorIdAsync(int idFalda) {
            WearDropWA.FaldaWS.obtenerFaldaPorIdRequest inValue = new WearDropWA.FaldaWS.obtenerFaldaPorIdRequest();
            inValue.idFalda = idFalda;
            return ((WearDropWA.FaldaWS.FaldaWS)(this)).obtenerFaldaPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.FaldaWS.listarFaldasResponse WearDropWA.FaldaWS.FaldaWS.listarFaldas(WearDropWA.FaldaWS.listarFaldasRequest request) {
            return base.Channel.listarFaldas(request);
        }
        
        public WearDropWA.FaldaWS.falda[] listarFaldas() {
            WearDropWA.FaldaWS.listarFaldasRequest inValue = new WearDropWA.FaldaWS.listarFaldasRequest();
            WearDropWA.FaldaWS.listarFaldasResponse retVal = ((WearDropWA.FaldaWS.FaldaWS)(this)).listarFaldas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.FaldaWS.listarFaldasResponse> WearDropWA.FaldaWS.FaldaWS.listarFaldasAsync(WearDropWA.FaldaWS.listarFaldasRequest request) {
            return base.Channel.listarFaldasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.FaldaWS.listarFaldasResponse> listarFaldasAsync() {
            WearDropWA.FaldaWS.listarFaldasRequest inValue = new WearDropWA.FaldaWS.listarFaldasRequest();
            return ((WearDropWA.FaldaWS.FaldaWS)(this)).listarFaldasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.FaldaWS.eliminarFaldaResponse WearDropWA.FaldaWS.FaldaWS.eliminarFalda(WearDropWA.FaldaWS.eliminarFaldaRequest request) {
            return base.Channel.eliminarFalda(request);
        }
        
        public int eliminarFalda(int idFalda) {
            WearDropWA.FaldaWS.eliminarFaldaRequest inValue = new WearDropWA.FaldaWS.eliminarFaldaRequest();
            inValue.idFalda = idFalda;
            WearDropWA.FaldaWS.eliminarFaldaResponse retVal = ((WearDropWA.FaldaWS.FaldaWS)(this)).eliminarFalda(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.FaldaWS.eliminarFaldaResponse> WearDropWA.FaldaWS.FaldaWS.eliminarFaldaAsync(WearDropWA.FaldaWS.eliminarFaldaRequest request) {
            return base.Channel.eliminarFaldaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.FaldaWS.eliminarFaldaResponse> eliminarFaldaAsync(int idFalda) {
            WearDropWA.FaldaWS.eliminarFaldaRequest inValue = new WearDropWA.FaldaWS.eliminarFaldaRequest();
            inValue.idFalda = idFalda;
            return ((WearDropWA.FaldaWS.FaldaWS)(this)).eliminarFaldaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.FaldaWS.filtrarFaldasResponse WearDropWA.FaldaWS.FaldaWS.filtrarFaldas(WearDropWA.FaldaWS.filtrarFaldasRequest request) {
            return base.Channel.filtrarFaldas(request);
        }
        
        public WearDropWA.FaldaWS.falda[] filtrarFaldas(string nombreLike, string colorLike, string materialLike, string tipoFaldaLike, bool conForro, bool conVolantes, double precioMin, double precioMax, double largoMin, double largoMax, bool soloActivos) {
            WearDropWA.FaldaWS.filtrarFaldasRequest inValue = new WearDropWA.FaldaWS.filtrarFaldasRequest();
            inValue.nombreLike = nombreLike;
            inValue.colorLike = colorLike;
            inValue.materialLike = materialLike;
            inValue.tipoFaldaLike = tipoFaldaLike;
            inValue.conForro = conForro;
            inValue.conVolantes = conVolantes;
            inValue.precioMin = precioMin;
            inValue.precioMax = precioMax;
            inValue.largoMin = largoMin;
            inValue.largoMax = largoMax;
            inValue.soloActivos = soloActivos;
            WearDropWA.FaldaWS.filtrarFaldasResponse retVal = ((WearDropWA.FaldaWS.FaldaWS)(this)).filtrarFaldas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.FaldaWS.filtrarFaldasResponse> WearDropWA.FaldaWS.FaldaWS.filtrarFaldasAsync(WearDropWA.FaldaWS.filtrarFaldasRequest request) {
            return base.Channel.filtrarFaldasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.FaldaWS.filtrarFaldasResponse> filtrarFaldasAsync(string nombreLike, string colorLike, string materialLike, string tipoFaldaLike, bool conForro, bool conVolantes, double precioMin, double precioMax, double largoMin, double largoMax, bool soloActivos) {
            WearDropWA.FaldaWS.filtrarFaldasRequest inValue = new WearDropWA.FaldaWS.filtrarFaldasRequest();
            inValue.nombreLike = nombreLike;
            inValue.colorLike = colorLike;
            inValue.materialLike = materialLike;
            inValue.tipoFaldaLike = tipoFaldaLike;
            inValue.conForro = conForro;
            inValue.conVolantes = conVolantes;
            inValue.precioMin = precioMin;
            inValue.precioMax = precioMax;
            inValue.largoMin = largoMin;
            inValue.largoMax = largoMax;
            inValue.soloActivos = soloActivos;
            return ((WearDropWA.FaldaWS.FaldaWS)(this)).filtrarFaldasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.FaldaWS.insertarFaldaResponse WearDropWA.FaldaWS.FaldaWS.insertarFalda(WearDropWA.FaldaWS.insertarFaldaRequest request) {
            return base.Channel.insertarFalda(request);
        }
        
        public int insertarFalda(WearDropWA.FaldaWS.falda falda) {
            WearDropWA.FaldaWS.insertarFaldaRequest inValue = new WearDropWA.FaldaWS.insertarFaldaRequest();
            inValue.falda = falda;
            WearDropWA.FaldaWS.insertarFaldaResponse retVal = ((WearDropWA.FaldaWS.FaldaWS)(this)).insertarFalda(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.FaldaWS.insertarFaldaResponse> WearDropWA.FaldaWS.FaldaWS.insertarFaldaAsync(WearDropWA.FaldaWS.insertarFaldaRequest request) {
            return base.Channel.insertarFaldaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.FaldaWS.insertarFaldaResponse> insertarFaldaAsync(WearDropWA.FaldaWS.falda falda) {
            WearDropWA.FaldaWS.insertarFaldaRequest inValue = new WearDropWA.FaldaWS.insertarFaldaRequest();
            inValue.falda = falda;
            return ((WearDropWA.FaldaWS.FaldaWS)(this)).insertarFaldaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.FaldaWS.modificarFaldaResponse WearDropWA.FaldaWS.FaldaWS.modificarFalda(WearDropWA.FaldaWS.modificarFaldaRequest request) {
            return base.Channel.modificarFalda(request);
        }
        
        public int modificarFalda(WearDropWA.FaldaWS.falda falda) {
            WearDropWA.FaldaWS.modificarFaldaRequest inValue = new WearDropWA.FaldaWS.modificarFaldaRequest();
            inValue.falda = falda;
            WearDropWA.FaldaWS.modificarFaldaResponse retVal = ((WearDropWA.FaldaWS.FaldaWS)(this)).modificarFalda(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.FaldaWS.modificarFaldaResponse> WearDropWA.FaldaWS.FaldaWS.modificarFaldaAsync(WearDropWA.FaldaWS.modificarFaldaRequest request) {
            return base.Channel.modificarFaldaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.FaldaWS.modificarFaldaResponse> modificarFaldaAsync(WearDropWA.FaldaWS.falda falda) {
            WearDropWA.FaldaWS.modificarFaldaRequest inValue = new WearDropWA.FaldaWS.modificarFaldaRequest();
            inValue.falda = falda;
            return ((WearDropWA.FaldaWS.FaldaWS)(this)).modificarFaldaAsync(inValue);
        }
    }
}
