//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WearDropWA.ServiciosDeDescuentoLiquidacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/", ConfigurationName="ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS")]
    public interface DescuentoLiquidacionWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/helloReque" +
            "st", ReplyAction="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/helloRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.ServiciosDeDescuentoLiquidacion.helloResponse hello(WearDropWA.ServiciosDeDescuentoLiquidacion.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/helloReque" +
            "st", ReplyAction="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/helloRespo" +
            "nse")]
        System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.helloResponse> helloAsync(WearDropWA.ServiciosDeDescuentoLiquidacion.helloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/mostrar_de" +
            "scuentosliquidacionRequest", ReplyAction="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/mostrar_de" +
            "scuentosliquidacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosliquidacionResponse mostrar_descuentosliquidacion(WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosliquidacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/mostrar_de" +
            "scuentosliquidacionRequest", ReplyAction="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/mostrar_de" +
            "scuentosliquidacionResponse")]
        System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosliquidacionResponse> mostrar_descuentosliquidacionAsync(WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosliquidacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/eliminarDe" +
            "scuentoLiquidacionRequest", ReplyAction="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/eliminarDe" +
            "scuentoLiquidacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.ServiciosDeDescuentoLiquidacion.eliminarDescuentoLiquidacionResponse eliminarDescuentoLiquidacion(WearDropWA.ServiciosDeDescuentoLiquidacion.eliminarDescuentoLiquidacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/eliminarDe" +
            "scuentoLiquidacionRequest", ReplyAction="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/eliminarDe" +
            "scuentoLiquidacionResponse")]
        System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.eliminarDescuentoLiquidacionResponse> eliminarDescuentoLiquidacionAsync(WearDropWA.ServiciosDeDescuentoLiquidacion.eliminarDescuentoLiquidacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/modificarD" +
            "ecuentoLiquidacionRequest", ReplyAction="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/modificarD" +
            "ecuentoLiquidacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.ServiciosDeDescuentoLiquidacion.modificarDecuentoLiquidacionResponse modificarDecuentoLiquidacion(WearDropWA.ServiciosDeDescuentoLiquidacion.modificarDecuentoLiquidacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/modificarD" +
            "ecuentoLiquidacionRequest", ReplyAction="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/modificarD" +
            "ecuentoLiquidacionResponse")]
        System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.modificarDecuentoLiquidacionResponse> modificarDecuentoLiquidacionAsync(WearDropWA.ServiciosDeDescuentoLiquidacion.modificarDecuentoLiquidacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/obtenerPor" +
            "IdRequest", ReplyAction="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/obtenerPor" +
            "IdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.ServiciosDeDescuentoLiquidacion.obtenerPorIdResponse obtenerPorId(WearDropWA.ServiciosDeDescuentoLiquidacion.obtenerPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/obtenerPor" +
            "IdRequest", ReplyAction="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/obtenerPor" +
            "IdResponse")]
        System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.obtenerPorIdResponse> obtenerPorIdAsync(WearDropWA.ServiciosDeDescuentoLiquidacion.obtenerPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/mostrar_de" +
            "scuentosActivosRequest", ReplyAction="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/mostrar_de" +
            "scuentosActivosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosActivosResponse mostrar_descuentosActivos(WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosActivosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/mostrar_de" +
            "scuentosActivosRequest", ReplyAction="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/mostrar_de" +
            "scuentosActivosResponse")]
        System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosActivosResponse> mostrar_descuentosActivosAsync(WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosActivosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/insertarDe" +
            "scuentoRequest", ReplyAction="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/insertarDe" +
            "scuentoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.ServiciosDeDescuentoLiquidacion.insertarDescuentoResponse insertarDescuento(WearDropWA.ServiciosDeDescuentoLiquidacion.insertarDescuentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/insertarDe" +
            "scuentoRequest", ReplyAction="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/insertarDe" +
            "scuentoResponse")]
        System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.insertarDescuentoResponse> insertarDescuentoAsync(WearDropWA.ServiciosDeDescuentoLiquidacion.insertarDescuentoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/insertar_p" +
            "rendadescuentoRequest", ReplyAction="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/insertar_p" +
            "rendadescuentoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.ServiciosDeDescuentoLiquidacion.insertar_prendadescuentoResponse insertar_prendadescuento(WearDropWA.ServiciosDeDescuentoLiquidacion.insertar_prendadescuentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/insertar_p" +
            "rendadescuentoRequest", ReplyAction="http://descuentos.services.weardrop.pucp.edu.pe/DescuentoLiquidacionWS/insertar_p" +
            "rendadescuentoResponse")]
        System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.insertar_prendadescuentoResponse> insertar_prendadescuentoAsync(WearDropWA.ServiciosDeDescuentoLiquidacion.insertar_prendadescuentoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://descuentos.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://descuentos.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/")]
    public partial class descuentoLiquidacion : descuento {
        
        private int condicionStockMinField;
        
        private double porcentajeLiquidacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int condicionStockMin {
            get {
                return this.condicionStockMinField;
            }
            set {
                this.condicionStockMinField = value;
                this.RaisePropertyChanged("condicionStockMin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double porcentajeLiquidacion {
            get {
                return this.porcentajeLiquidacionField;
            }
            set {
                this.porcentajeLiquidacionField = value;
                this.RaisePropertyChanged("porcentajeLiquidacion");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(descuentoLiquidacion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/")]
    public abstract partial class descuento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool esAutomaticoField;
        
        private int idDescuentoField;
        
        private string nombreField;
        
        private vigencia vigenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool esAutomatico {
            get {
                return this.esAutomaticoField;
            }
            set {
                this.esAutomaticoField = value;
                this.RaisePropertyChanged("esAutomatico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idDescuento {
            get {
                return this.idDescuentoField;
            }
            set {
                this.idDescuentoField = value;
                this.RaisePropertyChanged("idDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public vigencia vigencia {
            get {
                return this.vigenciaField;
            }
            set {
                this.vigenciaField = value;
                this.RaisePropertyChanged("vigencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/")]
    public partial class vigencia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idVigenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idVigencia {
            get {
                return this.idVigenciaField;
            }
            set {
                this.idVigenciaField = value;
                this.RaisePropertyChanged("idVigencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/")]
    public abstract partial class promocion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool esAutomaticoField;
        
        private int idPromocionField;
        
        private string nombreField;
        
        private vigencia vigenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool esAutomatico {
            get {
                return this.esAutomaticoField;
            }
            set {
                this.esAutomaticoField = value;
                this.RaisePropertyChanged("esAutomatico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idPromocion {
            get {
                return this.idPromocionField;
            }
            set {
                this.idPromocionField = value;
                this.RaisePropertyChanged("idPromocion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public vigencia vigencia {
            get {
                return this.vigenciaField;
            }
            set {
                this.vigenciaField = value;
                this.RaisePropertyChanged("vigencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/")]
    public partial class almacen : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idField;
        
        private int idTiendaField;
        
        private string nombreField;
        
        private int stockField;
        
        private string ubicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idTienda {
            get {
                return this.idTiendaField;
            }
            set {
                this.idTiendaField = value;
                this.RaisePropertyChanged("idTienda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/")]
    public partial class lote : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private almacen datAlmacenField;
        
        private string descripcionField;
        
        private int idLoteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public almacen datAlmacen {
            get {
                return this.datAlmacenField;
            }
            set {
                this.datAlmacenField = value;
                this.RaisePropertyChanged("datAlmacen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idLote {
            get {
                return this.idLoteField;
            }
            set {
                this.idLoteField = value;
                this.RaisePropertyChanged("idLote");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/")]
    public abstract partial class prenda : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int alertaMinStockField;
        
        private string colorField;
        
        private descuento[] descuentosField;
        
        private int idPrendaField;
        
        private lote[] lotesField;
        
        private material materialField;
        
        private bool materialFieldSpecified;
        
        private string nombreField;
        
        private double precioDocenaField;
        
        private double precioMayorField;
        
        private double precioUnidadField;
        
        private promocion[] promocionesField;
        
        private int stockPrendaField;
        
        private System.Nullable<talla>[] tallaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int alertaMinStock {
            get {
                return this.alertaMinStockField;
            }
            set {
                this.alertaMinStockField = value;
                this.RaisePropertyChanged("alertaMinStock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("color");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("descuentos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public descuento[] descuentos {
            get {
                return this.descuentosField;
            }
            set {
                this.descuentosField = value;
                this.RaisePropertyChanged("descuentos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idPrenda {
            get {
                return this.idPrendaField;
            }
            set {
                this.idPrendaField = value;
                this.RaisePropertyChanged("idPrenda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lotes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public lote[] lotes {
            get {
                return this.lotesField;
            }
            set {
                this.lotesField = value;
                this.RaisePropertyChanged("lotes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public material material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
                this.RaisePropertyChanged("material");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool materialSpecified {
            get {
                return this.materialFieldSpecified;
            }
            set {
                this.materialFieldSpecified = value;
                this.RaisePropertyChanged("materialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double precioDocena {
            get {
                return this.precioDocenaField;
            }
            set {
                this.precioDocenaField = value;
                this.RaisePropertyChanged("precioDocena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double precioMayor {
            get {
                return this.precioMayorField;
            }
            set {
                this.precioMayorField = value;
                this.RaisePropertyChanged("precioMayor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double precioUnidad {
            get {
                return this.precioUnidadField;
            }
            set {
                this.precioUnidadField = value;
                this.RaisePropertyChanged("precioUnidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("promociones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public promocion[] promociones {
            get {
                return this.promocionesField;
            }
            set {
                this.promocionesField = value;
                this.RaisePropertyChanged("promociones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int stockPrenda {
            get {
                return this.stockPrendaField;
            }
            set {
                this.stockPrendaField = value;
                this.RaisePropertyChanged("stockPrenda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("talla", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public System.Nullable<talla>[] talla {
            get {
                return this.tallaField;
            }
            set {
                this.tallaField = value;
                this.RaisePropertyChanged("talla");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/")]
    public enum material {
        
        /// <remarks/>
        Algodon,
        
        /// <remarks/>
        Poliester,
        
        /// <remarks/>
        algodon_poliester,
        
        /// <remarks/>
        Lino,
        
        /// <remarks/>
        Rayon,
        
        /// <remarks/>
        Lana,
        
        /// <remarks/>
        Acrilico,
        
        /// <remarks/>
        Nylon,
        
        /// <remarks/>
        lycra,
        
        /// <remarks/>
        Denim,
        
        /// <remarks/>
        Drill,
        
        /// <remarks/>
        Gabardina,
        
        /// <remarks/>
        Polar,
        
        /// <remarks/>
        Franela,
        
        /// <remarks/>
        Cuero,
        
        /// <remarks/>
        Cuerina,
        
        /// <remarks/>
        Saten,
        
        /// <remarks/>
        Chifon,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/")]
    public enum talla {
        
        /// <remarks/>
        XS,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        XL,
        
        /// <remarks/>
        XXL,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mostrar_descuentosliquidacion", WrapperNamespace="http://descuentos.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class mostrar_descuentosliquidacionRequest {
        
        public mostrar_descuentosliquidacionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mostrar_descuentosliquidacionResponse", WrapperNamespace="http://descuentos.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class mostrar_descuentosliquidacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.ServiciosDeDescuentoLiquidacion.descuentoLiquidacion[] @return;
        
        public mostrar_descuentosliquidacionResponse() {
        }
        
        public mostrar_descuentosliquidacionResponse(WearDropWA.ServiciosDeDescuentoLiquidacion.descuentoLiquidacion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarDescuentoLiquidacion", WrapperNamespace="http://descuentos.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarDescuentoLiquidacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDesc;
        
        public eliminarDescuentoLiquidacionRequest() {
        }
        
        public eliminarDescuentoLiquidacionRequest(int idDesc) {
            this.idDesc = idDesc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarDescuentoLiquidacionResponse", WrapperNamespace="http://descuentos.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarDescuentoLiquidacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarDescuentoLiquidacionResponse() {
        }
        
        public eliminarDescuentoLiquidacionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarDecuentoLiquidacion", WrapperNamespace="http://descuentos.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarDecuentoLiquidacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.ServiciosDeDescuentoLiquidacion.descuentoLiquidacion datDesc;
        
        public modificarDecuentoLiquidacionRequest() {
        }
        
        public modificarDecuentoLiquidacionRequest(WearDropWA.ServiciosDeDescuentoLiquidacion.descuentoLiquidacion datDesc) {
            this.datDesc = datDesc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarDecuentoLiquidacionResponse", WrapperNamespace="http://descuentos.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarDecuentoLiquidacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarDecuentoLiquidacionResponse() {
        }
        
        public modificarDecuentoLiquidacionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorId", WrapperNamespace="http://descuentos.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDesc;
        
        public obtenerPorIdRequest() {
        }
        
        public obtenerPorIdRequest(int idDesc) {
            this.idDesc = idDesc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdResponse", WrapperNamespace="http://descuentos.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.ServiciosDeDescuentoLiquidacion.descuentoLiquidacion @return;
        
        public obtenerPorIdResponse() {
        }
        
        public obtenerPorIdResponse(WearDropWA.ServiciosDeDescuentoLiquidacion.descuentoLiquidacion @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mostrar_descuentosActivos", WrapperNamespace="http://descuentos.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class mostrar_descuentosActivosRequest {
        
        public mostrar_descuentosActivosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mostrar_descuentosActivosResponse", WrapperNamespace="http://descuentos.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class mostrar_descuentosActivosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.ServiciosDeDescuentoLiquidacion.descuentoLiquidacion[] @return;
        
        public mostrar_descuentosActivosResponse() {
        }
        
        public mostrar_descuentosActivosResponse(WearDropWA.ServiciosDeDescuentoLiquidacion.descuentoLiquidacion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarDescuento", WrapperNamespace="http://descuentos.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarDescuentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.ServiciosDeDescuentoLiquidacion.descuentoLiquidacion datDesc;
        
        public insertarDescuentoRequest() {
        }
        
        public insertarDescuentoRequest(WearDropWA.ServiciosDeDescuentoLiquidacion.descuentoLiquidacion datDesc) {
            this.datDesc = datDesc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarDescuentoResponse", WrapperNamespace="http://descuentos.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarDescuentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarDescuentoResponse() {
        }
        
        public insertarDescuentoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar_prendadescuento", WrapperNamespace="http://descuentos.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertar_prendadescuentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.ServiciosDeDescuentoLiquidacion.descuentoLiquidacion datDesc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("prendas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.ServiciosDeDescuentoLiquidacion.prenda[] prendas;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.ServiciosDeDescuentoLiquidacion.vigencia vig;
        
        public insertar_prendadescuentoRequest() {
        }
        
        public insertar_prendadescuentoRequest(WearDropWA.ServiciosDeDescuentoLiquidacion.descuentoLiquidacion datDesc, WearDropWA.ServiciosDeDescuentoLiquidacion.prenda[] prendas, WearDropWA.ServiciosDeDescuentoLiquidacion.vigencia vig) {
            this.datDesc = datDesc;
            this.prendas = prendas;
            this.vig = vig;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar_prendadescuentoResponse", WrapperNamespace="http://descuentos.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertar_prendadescuentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://descuentos.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertar_prendadescuentoResponse() {
        }
        
        public insertar_prendadescuentoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DescuentoLiquidacionWSChannel : WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DescuentoLiquidacionWSClient : System.ServiceModel.ClientBase<WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS>, WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS {
        
        public DescuentoLiquidacionWSClient() {
        }
        
        public DescuentoLiquidacionWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DescuentoLiquidacionWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DescuentoLiquidacionWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DescuentoLiquidacionWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.ServiciosDeDescuentoLiquidacion.helloResponse WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS.hello(WearDropWA.ServiciosDeDescuentoLiquidacion.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            WearDropWA.ServiciosDeDescuentoLiquidacion.helloRequest inValue = new WearDropWA.ServiciosDeDescuentoLiquidacion.helloRequest();
            inValue.name = name;
            WearDropWA.ServiciosDeDescuentoLiquidacion.helloResponse retVal = ((WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.helloResponse> WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS.helloAsync(WearDropWA.ServiciosDeDescuentoLiquidacion.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.helloResponse> helloAsync(string name) {
            WearDropWA.ServiciosDeDescuentoLiquidacion.helloRequest inValue = new WearDropWA.ServiciosDeDescuentoLiquidacion.helloRequest();
            inValue.name = name;
            return ((WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosliquidacionResponse WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS.mostrar_descuentosliquidacion(WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosliquidacionRequest request) {
            return base.Channel.mostrar_descuentosliquidacion(request);
        }
        
        public WearDropWA.ServiciosDeDescuentoLiquidacion.descuentoLiquidacion[] mostrar_descuentosliquidacion() {
            WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosliquidacionRequest inValue = new WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosliquidacionRequest();
            WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosliquidacionResponse retVal = ((WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS)(this)).mostrar_descuentosliquidacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosliquidacionResponse> WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS.mostrar_descuentosliquidacionAsync(WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosliquidacionRequest request) {
            return base.Channel.mostrar_descuentosliquidacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosliquidacionResponse> mostrar_descuentosliquidacionAsync() {
            WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosliquidacionRequest inValue = new WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosliquidacionRequest();
            return ((WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS)(this)).mostrar_descuentosliquidacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.ServiciosDeDescuentoLiquidacion.eliminarDescuentoLiquidacionResponse WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS.eliminarDescuentoLiquidacion(WearDropWA.ServiciosDeDescuentoLiquidacion.eliminarDescuentoLiquidacionRequest request) {
            return base.Channel.eliminarDescuentoLiquidacion(request);
        }
        
        public int eliminarDescuentoLiquidacion(int idDesc) {
            WearDropWA.ServiciosDeDescuentoLiquidacion.eliminarDescuentoLiquidacionRequest inValue = new WearDropWA.ServiciosDeDescuentoLiquidacion.eliminarDescuentoLiquidacionRequest();
            inValue.idDesc = idDesc;
            WearDropWA.ServiciosDeDescuentoLiquidacion.eliminarDescuentoLiquidacionResponse retVal = ((WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS)(this)).eliminarDescuentoLiquidacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.eliminarDescuentoLiquidacionResponse> WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS.eliminarDescuentoLiquidacionAsync(WearDropWA.ServiciosDeDescuentoLiquidacion.eliminarDescuentoLiquidacionRequest request) {
            return base.Channel.eliminarDescuentoLiquidacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.eliminarDescuentoLiquidacionResponse> eliminarDescuentoLiquidacionAsync(int idDesc) {
            WearDropWA.ServiciosDeDescuentoLiquidacion.eliminarDescuentoLiquidacionRequest inValue = new WearDropWA.ServiciosDeDescuentoLiquidacion.eliminarDescuentoLiquidacionRequest();
            inValue.idDesc = idDesc;
            return ((WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS)(this)).eliminarDescuentoLiquidacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.ServiciosDeDescuentoLiquidacion.modificarDecuentoLiquidacionResponse WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS.modificarDecuentoLiquidacion(WearDropWA.ServiciosDeDescuentoLiquidacion.modificarDecuentoLiquidacionRequest request) {
            return base.Channel.modificarDecuentoLiquidacion(request);
        }
        
        public int modificarDecuentoLiquidacion(WearDropWA.ServiciosDeDescuentoLiquidacion.descuentoLiquidacion datDesc) {
            WearDropWA.ServiciosDeDescuentoLiquidacion.modificarDecuentoLiquidacionRequest inValue = new WearDropWA.ServiciosDeDescuentoLiquidacion.modificarDecuentoLiquidacionRequest();
            inValue.datDesc = datDesc;
            WearDropWA.ServiciosDeDescuentoLiquidacion.modificarDecuentoLiquidacionResponse retVal = ((WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS)(this)).modificarDecuentoLiquidacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.modificarDecuentoLiquidacionResponse> WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS.modificarDecuentoLiquidacionAsync(WearDropWA.ServiciosDeDescuentoLiquidacion.modificarDecuentoLiquidacionRequest request) {
            return base.Channel.modificarDecuentoLiquidacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.modificarDecuentoLiquidacionResponse> modificarDecuentoLiquidacionAsync(WearDropWA.ServiciosDeDescuentoLiquidacion.descuentoLiquidacion datDesc) {
            WearDropWA.ServiciosDeDescuentoLiquidacion.modificarDecuentoLiquidacionRequest inValue = new WearDropWA.ServiciosDeDescuentoLiquidacion.modificarDecuentoLiquidacionRequest();
            inValue.datDesc = datDesc;
            return ((WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS)(this)).modificarDecuentoLiquidacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.ServiciosDeDescuentoLiquidacion.obtenerPorIdResponse WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS.obtenerPorId(WearDropWA.ServiciosDeDescuentoLiquidacion.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorId(request);
        }
        
        public WearDropWA.ServiciosDeDescuentoLiquidacion.descuentoLiquidacion obtenerPorId(int idDesc) {
            WearDropWA.ServiciosDeDescuentoLiquidacion.obtenerPorIdRequest inValue = new WearDropWA.ServiciosDeDescuentoLiquidacion.obtenerPorIdRequest();
            inValue.idDesc = idDesc;
            WearDropWA.ServiciosDeDescuentoLiquidacion.obtenerPorIdResponse retVal = ((WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS)(this)).obtenerPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.obtenerPorIdResponse> WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS.obtenerPorIdAsync(WearDropWA.ServiciosDeDescuentoLiquidacion.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.obtenerPorIdResponse> obtenerPorIdAsync(int idDesc) {
            WearDropWA.ServiciosDeDescuentoLiquidacion.obtenerPorIdRequest inValue = new WearDropWA.ServiciosDeDescuentoLiquidacion.obtenerPorIdRequest();
            inValue.idDesc = idDesc;
            return ((WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS)(this)).obtenerPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosActivosResponse WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS.mostrar_descuentosActivos(WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosActivosRequest request) {
            return base.Channel.mostrar_descuentosActivos(request);
        }
        
        public WearDropWA.ServiciosDeDescuentoLiquidacion.descuentoLiquidacion[] mostrar_descuentosActivos() {
            WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosActivosRequest inValue = new WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosActivosRequest();
            WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosActivosResponse retVal = ((WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS)(this)).mostrar_descuentosActivos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosActivosResponse> WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS.mostrar_descuentosActivosAsync(WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosActivosRequest request) {
            return base.Channel.mostrar_descuentosActivosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosActivosResponse> mostrar_descuentosActivosAsync() {
            WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosActivosRequest inValue = new WearDropWA.ServiciosDeDescuentoLiquidacion.mostrar_descuentosActivosRequest();
            return ((WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS)(this)).mostrar_descuentosActivosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.ServiciosDeDescuentoLiquidacion.insertarDescuentoResponse WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS.insertarDescuento(WearDropWA.ServiciosDeDescuentoLiquidacion.insertarDescuentoRequest request) {
            return base.Channel.insertarDescuento(request);
        }
        
        public int insertarDescuento(WearDropWA.ServiciosDeDescuentoLiquidacion.descuentoLiquidacion datDesc) {
            WearDropWA.ServiciosDeDescuentoLiquidacion.insertarDescuentoRequest inValue = new WearDropWA.ServiciosDeDescuentoLiquidacion.insertarDescuentoRequest();
            inValue.datDesc = datDesc;
            WearDropWA.ServiciosDeDescuentoLiquidacion.insertarDescuentoResponse retVal = ((WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS)(this)).insertarDescuento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.insertarDescuentoResponse> WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS.insertarDescuentoAsync(WearDropWA.ServiciosDeDescuentoLiquidacion.insertarDescuentoRequest request) {
            return base.Channel.insertarDescuentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.insertarDescuentoResponse> insertarDescuentoAsync(WearDropWA.ServiciosDeDescuentoLiquidacion.descuentoLiquidacion datDesc) {
            WearDropWA.ServiciosDeDescuentoLiquidacion.insertarDescuentoRequest inValue = new WearDropWA.ServiciosDeDescuentoLiquidacion.insertarDescuentoRequest();
            inValue.datDesc = datDesc;
            return ((WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS)(this)).insertarDescuentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.ServiciosDeDescuentoLiquidacion.insertar_prendadescuentoResponse WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS.insertar_prendadescuento(WearDropWA.ServiciosDeDescuentoLiquidacion.insertar_prendadescuentoRequest request) {
            return base.Channel.insertar_prendadescuento(request);
        }
        
        public int insertar_prendadescuento(WearDropWA.ServiciosDeDescuentoLiquidacion.descuentoLiquidacion datDesc, WearDropWA.ServiciosDeDescuentoLiquidacion.prenda[] prendas, WearDropWA.ServiciosDeDescuentoLiquidacion.vigencia vig) {
            WearDropWA.ServiciosDeDescuentoLiquidacion.insertar_prendadescuentoRequest inValue = new WearDropWA.ServiciosDeDescuentoLiquidacion.insertar_prendadescuentoRequest();
            inValue.datDesc = datDesc;
            inValue.prendas = prendas;
            inValue.vig = vig;
            WearDropWA.ServiciosDeDescuentoLiquidacion.insertar_prendadescuentoResponse retVal = ((WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS)(this)).insertar_prendadescuento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.insertar_prendadescuentoResponse> WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS.insertar_prendadescuentoAsync(WearDropWA.ServiciosDeDescuentoLiquidacion.insertar_prendadescuentoRequest request) {
            return base.Channel.insertar_prendadescuentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.ServiciosDeDescuentoLiquidacion.insertar_prendadescuentoResponse> insertar_prendadescuentoAsync(WearDropWA.ServiciosDeDescuentoLiquidacion.descuentoLiquidacion datDesc, WearDropWA.ServiciosDeDescuentoLiquidacion.prenda[] prendas, WearDropWA.ServiciosDeDescuentoLiquidacion.vigencia vig) {
            WearDropWA.ServiciosDeDescuentoLiquidacion.insertar_prendadescuentoRequest inValue = new WearDropWA.ServiciosDeDescuentoLiquidacion.insertar_prendadescuentoRequest();
            inValue.datDesc = datDesc;
            inValue.prendas = prendas;
            inValue.vig = vig;
            return ((WearDropWA.ServiciosDeDescuentoLiquidacion.DescuentoLiquidacionWS)(this)).insertar_prendadescuentoAsync(inValue);
        }
    }
}
