//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WearDropWA.CasacaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", ConfigurationName="CasacaWS.CasacaWS")]
    public interface CasacaWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/modificarCasacaRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/modificarCasacaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(prenda))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.CasacaWS.modificarCasacaResponse modificarCasaca(WearDropWA.CasacaWS.modificarCasacaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/modificarCasacaRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/modificarCasacaResponse")]
        System.Threading.Tasks.Task<WearDropWA.CasacaWS.modificarCasacaResponse> modificarCasacaAsync(WearDropWA.CasacaWS.modificarCasacaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/listarCasacasRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/listarCasacasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(prenda))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.CasacaWS.listarCasacasResponse listarCasacas(WearDropWA.CasacaWS.listarCasacasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/listarCasacasRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/listarCasacasResponse")]
        System.Threading.Tasks.Task<WearDropWA.CasacaWS.listarCasacasResponse> listarCasacasAsync(WearDropWA.CasacaWS.listarCasacasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/filtrarCasacasRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/filtrarCasacasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(prenda))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.CasacaWS.filtrarCasacasResponse filtrarCasacas(WearDropWA.CasacaWS.filtrarCasacasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/filtrarCasacasRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/filtrarCasacasResponse")]
        System.Threading.Tasks.Task<WearDropWA.CasacaWS.filtrarCasacasResponse> filtrarCasacasAsync(WearDropWA.CasacaWS.filtrarCasacasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/insertarCasacaRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/insertarCasacaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(prenda))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.CasacaWS.insertarCasacaResponse insertarCasaca(WearDropWA.CasacaWS.insertarCasacaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/insertarCasacaRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/insertarCasacaResponse")]
        System.Threading.Tasks.Task<WearDropWA.CasacaWS.insertarCasacaResponse> insertarCasacaAsync(WearDropWA.CasacaWS.insertarCasacaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/eliminarCasacaRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/eliminarCasacaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(prenda))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.CasacaWS.eliminarCasacaResponse eliminarCasaca(WearDropWA.CasacaWS.eliminarCasacaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/eliminarCasacaRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/eliminarCasacaResponse")]
        System.Threading.Tasks.Task<WearDropWA.CasacaWS.eliminarCasacaResponse> eliminarCasacaAsync(WearDropWA.CasacaWS.eliminarCasacaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/obtenerCasacaPorIdRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/obtenerCasacaPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(prenda))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.CasacaWS.obtenerCasacaPorIdResponse obtenerCasacaPorId(WearDropWA.CasacaWS.obtenerCasacaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/obtenerCasacaPorIdRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/CasacaWS/obtenerCasacaPorIdResponse")]
        System.Threading.Tasks.Task<WearDropWA.CasacaWS.obtenerCasacaPorIdResponse> obtenerCasacaPorIdAsync(WearDropWA.CasacaWS.obtenerCasacaPorIdRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public partial class casaca : prenda {
        
        private bool conCapuchaField;
        
        private tipoCasaca tipoCasacaField;
        
        private bool tipoCasacaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool conCapucha {
            get {
                return this.conCapuchaField;
            }
            set {
                this.conCapuchaField = value;
                this.RaisePropertyChanged("conCapucha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public tipoCasaca tipoCasaca {
            get {
                return this.tipoCasacaField;
            }
            set {
                this.tipoCasacaField = value;
                this.RaisePropertyChanged("tipoCasaca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoCasacaSpecified {
            get {
                return this.tipoCasacaFieldSpecified;
            }
            set {
                this.tipoCasacaFieldSpecified = value;
                this.RaisePropertyChanged("tipoCasacaSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public enum tipoCasaca {
        
        /// <remarks/>
        Bomber,
        
        /// <remarks/>
        Puffer,
        
        /// <remarks/>
        Denim,
        
        /// <remarks/>
        Deportiva,
        
        /// <remarks/>
        Cuero,
        
        /// <remarks/>
        Cardigan,
        
        /// <remarks/>
        Otro,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(casaca))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public abstract partial class prenda : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int alertaMinStockField;
        
        private string colorField;
        
        private descuento[] descuentosField;
        
        private int idPrendaField;
        
        private lote[] lotesField;
        
        private material materialField;
        
        private bool materialFieldSpecified;
        
        private string nombreField;
        
        private double precioDocenaField;
        
        private double precioMayorField;
        
        private double precioUnidadField;
        
        private promocion[] promocionesField;
        
        private int stockPrendaField;
        
        private System.Nullable<talla>[] tallaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int alertaMinStock {
            get {
                return this.alertaMinStockField;
            }
            set {
                this.alertaMinStockField = value;
                this.RaisePropertyChanged("alertaMinStock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("color");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("descuentos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public descuento[] descuentos {
            get {
                return this.descuentosField;
            }
            set {
                this.descuentosField = value;
                this.RaisePropertyChanged("descuentos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idPrenda {
            get {
                return this.idPrendaField;
            }
            set {
                this.idPrendaField = value;
                this.RaisePropertyChanged("idPrenda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lotes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public lote[] lotes {
            get {
                return this.lotesField;
            }
            set {
                this.lotesField = value;
                this.RaisePropertyChanged("lotes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public material material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
                this.RaisePropertyChanged("material");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool materialSpecified {
            get {
                return this.materialFieldSpecified;
            }
            set {
                this.materialFieldSpecified = value;
                this.RaisePropertyChanged("materialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double precioDocena {
            get {
                return this.precioDocenaField;
            }
            set {
                this.precioDocenaField = value;
                this.RaisePropertyChanged("precioDocena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double precioMayor {
            get {
                return this.precioMayorField;
            }
            set {
                this.precioMayorField = value;
                this.RaisePropertyChanged("precioMayor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double precioUnidad {
            get {
                return this.precioUnidadField;
            }
            set {
                this.precioUnidadField = value;
                this.RaisePropertyChanged("precioUnidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("promociones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public promocion[] promociones {
            get {
                return this.promocionesField;
            }
            set {
                this.promocionesField = value;
                this.RaisePropertyChanged("promociones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int stockPrenda {
            get {
                return this.stockPrendaField;
            }
            set {
                this.stockPrendaField = value;
                this.RaisePropertyChanged("stockPrenda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("talla", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public System.Nullable<talla>[] talla {
            get {
                return this.tallaField;
            }
            set {
                this.tallaField = value;
                this.RaisePropertyChanged("talla");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public abstract partial class descuento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool esAutomaticoField;
        
        private int idDescuentoField;
        
        private string nombreField;
        
        private vigencia vigenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool esAutomatico {
            get {
                return this.esAutomaticoField;
            }
            set {
                this.esAutomaticoField = value;
                this.RaisePropertyChanged("esAutomatico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idDescuento {
            get {
                return this.idDescuentoField;
            }
            set {
                this.idDescuentoField = value;
                this.RaisePropertyChanged("idDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public vigencia vigencia {
            get {
                return this.vigenciaField;
            }
            set {
                this.vigenciaField = value;
                this.RaisePropertyChanged("vigencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public partial class vigencia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idVigenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idVigencia {
            get {
                return this.idVigenciaField;
            }
            set {
                this.idVigenciaField = value;
                this.RaisePropertyChanged("idVigencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public abstract partial class promocion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool esAutomaticoField;
        
        private int idPromocionField;
        
        private string nombreField;
        
        private vigencia vigenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool esAutomatico {
            get {
                return this.esAutomaticoField;
            }
            set {
                this.esAutomaticoField = value;
                this.RaisePropertyChanged("esAutomatico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idPromocion {
            get {
                return this.idPromocionField;
            }
            set {
                this.idPromocionField = value;
                this.RaisePropertyChanged("idPromocion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public vigencia vigencia {
            get {
                return this.vigenciaField;
            }
            set {
                this.vigenciaField = value;
                this.RaisePropertyChanged("vigencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public partial class almacen : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idField;
        
        private int idTiendaField;
        
        private string nombreField;
        
        private int stockField;
        
        private string ubicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idTienda {
            get {
                return this.idTiendaField;
            }
            set {
                this.idTiendaField = value;
                this.RaisePropertyChanged("idTienda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public partial class lote : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private almacen datAlmacenField;
        
        private string descripcionField;
        
        private int idLoteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public almacen datAlmacen {
            get {
                return this.datAlmacenField;
            }
            set {
                this.datAlmacenField = value;
                this.RaisePropertyChanged("datAlmacen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idLote {
            get {
                return this.idLoteField;
            }
            set {
                this.idLoteField = value;
                this.RaisePropertyChanged("idLote");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public enum material {
        
        /// <remarks/>
        Algodon,
        
        /// <remarks/>
        Poliester,
        
        /// <remarks/>
        algodon_poliester,
        
        /// <remarks/>
        Lino,
        
        /// <remarks/>
        Rayon,
        
        /// <remarks/>
        Lana,
        
        /// <remarks/>
        Acrilico,
        
        /// <remarks/>
        Nylon,
        
        /// <remarks/>
        lycra,
        
        /// <remarks/>
        Denim,
        
        /// <remarks/>
        Drill,
        
        /// <remarks/>
        Gabardina,
        
        /// <remarks/>
        Polar,
        
        /// <remarks/>
        Franela,
        
        /// <remarks/>
        Cuero,
        
        /// <remarks/>
        Cuerina,
        
        /// <remarks/>
        Saten,
        
        /// <remarks/>
        Chifon,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public enum talla {
        
        /// <remarks/>
        XS,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        XL,
        
        /// <remarks/>
        XXL,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCasaca", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCasacaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.CasacaWS.casaca casaca;
        
        public modificarCasacaRequest() {
        }
        
        public modificarCasacaRequest(WearDropWA.CasacaWS.casaca casaca) {
            this.casaca = casaca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCasacaResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCasacaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarCasacaResponse() {
        }
        
        public modificarCasacaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCasacas", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCasacasRequest {
        
        public listarCasacasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCasacasResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCasacasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.CasacaWS.casaca[] @return;
        
        public listarCasacasResponse() {
        }
        
        public listarCasacasResponse(WearDropWA.CasacaWS.casaca[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="filtrarCasacas", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class filtrarCasacasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreLike;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string colorLike;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string materialLike;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoCasacaLike;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool conCapucha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double precioMin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double precioMax;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool soloActivos;
        
        public filtrarCasacasRequest() {
        }
        
        public filtrarCasacasRequest(string nombreLike, string colorLike, string materialLike, string tipoCasacaLike, bool conCapucha, double precioMin, double precioMax, bool soloActivos) {
            this.nombreLike = nombreLike;
            this.colorLike = colorLike;
            this.materialLike = materialLike;
            this.tipoCasacaLike = tipoCasacaLike;
            this.conCapucha = conCapucha;
            this.precioMin = precioMin;
            this.precioMax = precioMax;
            this.soloActivos = soloActivos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="filtrarCasacasResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class filtrarCasacasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.CasacaWS.casaca[] @return;
        
        public filtrarCasacasResponse() {
        }
        
        public filtrarCasacasResponse(WearDropWA.CasacaWS.casaca[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCasaca", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCasacaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.CasacaWS.casaca casaca;
        
        public insertarCasacaRequest() {
        }
        
        public insertarCasacaRequest(WearDropWA.CasacaWS.casaca casaca) {
            this.casaca = casaca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCasacaResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCasacaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarCasacaResponse() {
        }
        
        public insertarCasacaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCasaca", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCasacaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCasaca;
        
        public eliminarCasacaRequest() {
        }
        
        public eliminarCasacaRequest(int idCasaca) {
            this.idCasaca = idCasaca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCasacaResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCasacaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarCasacaResponse() {
        }
        
        public eliminarCasacaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCasacaPorId", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCasacaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCasaca;
        
        public obtenerCasacaPorIdRequest() {
        }
        
        public obtenerCasacaPorIdRequest(int idCasaca) {
            this.idCasaca = idCasaca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCasacaPorIdResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCasacaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.CasacaWS.casaca @return;
        
        public obtenerCasacaPorIdResponse() {
        }
        
        public obtenerCasacaPorIdResponse(WearDropWA.CasacaWS.casaca @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CasacaWSChannel : WearDropWA.CasacaWS.CasacaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CasacaWSClient : System.ServiceModel.ClientBase<WearDropWA.CasacaWS.CasacaWS>, WearDropWA.CasacaWS.CasacaWS {
        
        public CasacaWSClient() {
        }
        
        public CasacaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CasacaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CasacaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CasacaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.CasacaWS.modificarCasacaResponse WearDropWA.CasacaWS.CasacaWS.modificarCasaca(WearDropWA.CasacaWS.modificarCasacaRequest request) {
            return base.Channel.modificarCasaca(request);
        }
        
        public int modificarCasaca(WearDropWA.CasacaWS.casaca casaca) {
            WearDropWA.CasacaWS.modificarCasacaRequest inValue = new WearDropWA.CasacaWS.modificarCasacaRequest();
            inValue.casaca = casaca;
            WearDropWA.CasacaWS.modificarCasacaResponse retVal = ((WearDropWA.CasacaWS.CasacaWS)(this)).modificarCasaca(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.CasacaWS.modificarCasacaResponse> WearDropWA.CasacaWS.CasacaWS.modificarCasacaAsync(WearDropWA.CasacaWS.modificarCasacaRequest request) {
            return base.Channel.modificarCasacaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.CasacaWS.modificarCasacaResponse> modificarCasacaAsync(WearDropWA.CasacaWS.casaca casaca) {
            WearDropWA.CasacaWS.modificarCasacaRequest inValue = new WearDropWA.CasacaWS.modificarCasacaRequest();
            inValue.casaca = casaca;
            return ((WearDropWA.CasacaWS.CasacaWS)(this)).modificarCasacaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.CasacaWS.listarCasacasResponse WearDropWA.CasacaWS.CasacaWS.listarCasacas(WearDropWA.CasacaWS.listarCasacasRequest request) {
            return base.Channel.listarCasacas(request);
        }
        
        public WearDropWA.CasacaWS.casaca[] listarCasacas() {
            WearDropWA.CasacaWS.listarCasacasRequest inValue = new WearDropWA.CasacaWS.listarCasacasRequest();
            WearDropWA.CasacaWS.listarCasacasResponse retVal = ((WearDropWA.CasacaWS.CasacaWS)(this)).listarCasacas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.CasacaWS.listarCasacasResponse> WearDropWA.CasacaWS.CasacaWS.listarCasacasAsync(WearDropWA.CasacaWS.listarCasacasRequest request) {
            return base.Channel.listarCasacasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.CasacaWS.listarCasacasResponse> listarCasacasAsync() {
            WearDropWA.CasacaWS.listarCasacasRequest inValue = new WearDropWA.CasacaWS.listarCasacasRequest();
            return ((WearDropWA.CasacaWS.CasacaWS)(this)).listarCasacasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.CasacaWS.filtrarCasacasResponse WearDropWA.CasacaWS.CasacaWS.filtrarCasacas(WearDropWA.CasacaWS.filtrarCasacasRequest request) {
            return base.Channel.filtrarCasacas(request);
        }
        
        public WearDropWA.CasacaWS.casaca[] filtrarCasacas(string nombreLike, string colorLike, string materialLike, string tipoCasacaLike, bool conCapucha, double precioMin, double precioMax, bool soloActivos) {
            WearDropWA.CasacaWS.filtrarCasacasRequest inValue = new WearDropWA.CasacaWS.filtrarCasacasRequest();
            inValue.nombreLike = nombreLike;
            inValue.colorLike = colorLike;
            inValue.materialLike = materialLike;
            inValue.tipoCasacaLike = tipoCasacaLike;
            inValue.conCapucha = conCapucha;
            inValue.precioMin = precioMin;
            inValue.precioMax = precioMax;
            inValue.soloActivos = soloActivos;
            WearDropWA.CasacaWS.filtrarCasacasResponse retVal = ((WearDropWA.CasacaWS.CasacaWS)(this)).filtrarCasacas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.CasacaWS.filtrarCasacasResponse> WearDropWA.CasacaWS.CasacaWS.filtrarCasacasAsync(WearDropWA.CasacaWS.filtrarCasacasRequest request) {
            return base.Channel.filtrarCasacasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.CasacaWS.filtrarCasacasResponse> filtrarCasacasAsync(string nombreLike, string colorLike, string materialLike, string tipoCasacaLike, bool conCapucha, double precioMin, double precioMax, bool soloActivos) {
            WearDropWA.CasacaWS.filtrarCasacasRequest inValue = new WearDropWA.CasacaWS.filtrarCasacasRequest();
            inValue.nombreLike = nombreLike;
            inValue.colorLike = colorLike;
            inValue.materialLike = materialLike;
            inValue.tipoCasacaLike = tipoCasacaLike;
            inValue.conCapucha = conCapucha;
            inValue.precioMin = precioMin;
            inValue.precioMax = precioMax;
            inValue.soloActivos = soloActivos;
            return ((WearDropWA.CasacaWS.CasacaWS)(this)).filtrarCasacasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.CasacaWS.insertarCasacaResponse WearDropWA.CasacaWS.CasacaWS.insertarCasaca(WearDropWA.CasacaWS.insertarCasacaRequest request) {
            return base.Channel.insertarCasaca(request);
        }
        
        public int insertarCasaca(WearDropWA.CasacaWS.casaca casaca) {
            WearDropWA.CasacaWS.insertarCasacaRequest inValue = new WearDropWA.CasacaWS.insertarCasacaRequest();
            inValue.casaca = casaca;
            WearDropWA.CasacaWS.insertarCasacaResponse retVal = ((WearDropWA.CasacaWS.CasacaWS)(this)).insertarCasaca(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.CasacaWS.insertarCasacaResponse> WearDropWA.CasacaWS.CasacaWS.insertarCasacaAsync(WearDropWA.CasacaWS.insertarCasacaRequest request) {
            return base.Channel.insertarCasacaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.CasacaWS.insertarCasacaResponse> insertarCasacaAsync(WearDropWA.CasacaWS.casaca casaca) {
            WearDropWA.CasacaWS.insertarCasacaRequest inValue = new WearDropWA.CasacaWS.insertarCasacaRequest();
            inValue.casaca = casaca;
            return ((WearDropWA.CasacaWS.CasacaWS)(this)).insertarCasacaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.CasacaWS.eliminarCasacaResponse WearDropWA.CasacaWS.CasacaWS.eliminarCasaca(WearDropWA.CasacaWS.eliminarCasacaRequest request) {
            return base.Channel.eliminarCasaca(request);
        }
        
        public int eliminarCasaca(int idCasaca) {
            WearDropWA.CasacaWS.eliminarCasacaRequest inValue = new WearDropWA.CasacaWS.eliminarCasacaRequest();
            inValue.idCasaca = idCasaca;
            WearDropWA.CasacaWS.eliminarCasacaResponse retVal = ((WearDropWA.CasacaWS.CasacaWS)(this)).eliminarCasaca(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.CasacaWS.eliminarCasacaResponse> WearDropWA.CasacaWS.CasacaWS.eliminarCasacaAsync(WearDropWA.CasacaWS.eliminarCasacaRequest request) {
            return base.Channel.eliminarCasacaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.CasacaWS.eliminarCasacaResponse> eliminarCasacaAsync(int idCasaca) {
            WearDropWA.CasacaWS.eliminarCasacaRequest inValue = new WearDropWA.CasacaWS.eliminarCasacaRequest();
            inValue.idCasaca = idCasaca;
            return ((WearDropWA.CasacaWS.CasacaWS)(this)).eliminarCasacaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.CasacaWS.obtenerCasacaPorIdResponse WearDropWA.CasacaWS.CasacaWS.obtenerCasacaPorId(WearDropWA.CasacaWS.obtenerCasacaPorIdRequest request) {
            return base.Channel.obtenerCasacaPorId(request);
        }
        
        public WearDropWA.CasacaWS.casaca obtenerCasacaPorId(int idCasaca) {
            WearDropWA.CasacaWS.obtenerCasacaPorIdRequest inValue = new WearDropWA.CasacaWS.obtenerCasacaPorIdRequest();
            inValue.idCasaca = idCasaca;
            WearDropWA.CasacaWS.obtenerCasacaPorIdResponse retVal = ((WearDropWA.CasacaWS.CasacaWS)(this)).obtenerCasacaPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.CasacaWS.obtenerCasacaPorIdResponse> WearDropWA.CasacaWS.CasacaWS.obtenerCasacaPorIdAsync(WearDropWA.CasacaWS.obtenerCasacaPorIdRequest request) {
            return base.Channel.obtenerCasacaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.CasacaWS.obtenerCasacaPorIdResponse> obtenerCasacaPorIdAsync(int idCasaca) {
            WearDropWA.CasacaWS.obtenerCasacaPorIdRequest inValue = new WearDropWA.CasacaWS.obtenerCasacaPorIdRequest();
            inValue.idCasaca = idCasaca;
            return ((WearDropWA.CasacaWS.CasacaWS)(this)).obtenerCasacaPorIdAsync(inValue);
        }
    }
}
