//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WearDropWA.GorroWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", ConfigurationName="GorroWS.GorroWS")]
    public interface GorroWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/eliminarGorroRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/eliminarGorroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.GorroWS.eliminarGorroResponse eliminarGorro(WearDropWA.GorroWS.eliminarGorroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/eliminarGorroRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/eliminarGorroResponse")]
        System.Threading.Tasks.Task<WearDropWA.GorroWS.eliminarGorroResponse> eliminarGorroAsync(WearDropWA.GorroWS.eliminarGorroRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/filtrarGorrosRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/filtrarGorrosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(prenda))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.GorroWS.filtrarGorrosResponse filtrarGorros(WearDropWA.GorroWS.filtrarGorrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/filtrarGorrosRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/filtrarGorrosResponse")]
        System.Threading.Tasks.Task<WearDropWA.GorroWS.filtrarGorrosResponse> filtrarGorrosAsync(WearDropWA.GorroWS.filtrarGorrosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/insertarGorroRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/insertarGorroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(prenda))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.GorroWS.insertarGorroResponse insertarGorro(WearDropWA.GorroWS.insertarGorroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/insertarGorroRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/insertarGorroResponse")]
        System.Threading.Tasks.Task<WearDropWA.GorroWS.insertarGorroResponse> insertarGorroAsync(WearDropWA.GorroWS.insertarGorroRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/obtenerGorroPorIdRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/obtenerGorroPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(prenda))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.GorroWS.obtenerGorroPorIdResponse obtenerGorroPorId(WearDropWA.GorroWS.obtenerGorroPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/obtenerGorroPorIdRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/obtenerGorroPorIdResponse")]
        System.Threading.Tasks.Task<WearDropWA.GorroWS.obtenerGorroPorIdResponse> obtenerGorroPorIdAsync(WearDropWA.GorroWS.obtenerGorroPorIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/modificarGorroRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/modificarGorroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(prenda))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.GorroWS.modificarGorroResponse modificarGorro(WearDropWA.GorroWS.modificarGorroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/modificarGorroRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/modificarGorroResponse")]
        System.Threading.Tasks.Task<WearDropWA.GorroWS.modificarGorroResponse> modificarGorroAsync(WearDropWA.GorroWS.modificarGorroRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/listarGorrosRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/listarGorrosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(prenda))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.GorroWS.listarGorrosResponse listarGorros(WearDropWA.GorroWS.listarGorrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/listarGorrosRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/GorroWS/listarGorrosResponse")]
        System.Threading.Tasks.Task<WearDropWA.GorroWS.listarGorrosResponse> listarGorrosAsync(WearDropWA.GorroWS.listarGorrosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarGorro", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarGorroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idGorro;
        
        public eliminarGorroRequest() {
        }
        
        public eliminarGorroRequest(int idGorro) {
            this.idGorro = idGorro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarGorroResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarGorroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarGorroResponse() {
        }
        
        public eliminarGorroResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public partial class gorro : prenda {
        
        private bool impermeableField;
        
        private bool tallaAjustableField;
        
        private tipoGorra tipoGorraField;
        
        private bool tipoGorraFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool impermeable {
            get {
                return this.impermeableField;
            }
            set {
                this.impermeableField = value;
                this.RaisePropertyChanged("impermeable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool tallaAjustable {
            get {
                return this.tallaAjustableField;
            }
            set {
                this.tallaAjustableField = value;
                this.RaisePropertyChanged("tallaAjustable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public tipoGorra tipoGorra {
            get {
                return this.tipoGorraField;
            }
            set {
                this.tipoGorraField = value;
                this.RaisePropertyChanged("tipoGorra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoGorraSpecified {
            get {
                return this.tipoGorraFieldSpecified;
            }
            set {
                this.tipoGorraFieldSpecified = value;
                this.RaisePropertyChanged("tipoGorraSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public enum tipoGorra {
        
        /// <remarks/>
        Bucket,
        
        /// <remarks/>
        Visera,
        
        /// <remarks/>
        Tejido,
        
        /// <remarks/>
        Beanie,
        
        /// <remarks/>
        Otro,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(gorro))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public abstract partial class prenda : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int alertaMinStockField;
        
        private string colorField;
        
        private descuento[] descuentosField;
        
        private int idPrendaField;
        
        private lote[] lotesField;
        
        private material materialField;
        
        private bool materialFieldSpecified;
        
        private string nombreField;
        
        private double precioDocenaField;
        
        private double precioMayorField;
        
        private double precioUnidadField;
        
        private promocion[] promocionesField;
        
        private int stockPrendaField;
        
        private System.Nullable<talla>[] tallaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int alertaMinStock {
            get {
                return this.alertaMinStockField;
            }
            set {
                this.alertaMinStockField = value;
                this.RaisePropertyChanged("alertaMinStock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("color");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("descuentos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public descuento[] descuentos {
            get {
                return this.descuentosField;
            }
            set {
                this.descuentosField = value;
                this.RaisePropertyChanged("descuentos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idPrenda {
            get {
                return this.idPrendaField;
            }
            set {
                this.idPrendaField = value;
                this.RaisePropertyChanged("idPrenda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lotes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public lote[] lotes {
            get {
                return this.lotesField;
            }
            set {
                this.lotesField = value;
                this.RaisePropertyChanged("lotes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public material material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
                this.RaisePropertyChanged("material");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool materialSpecified {
            get {
                return this.materialFieldSpecified;
            }
            set {
                this.materialFieldSpecified = value;
                this.RaisePropertyChanged("materialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double precioDocena {
            get {
                return this.precioDocenaField;
            }
            set {
                this.precioDocenaField = value;
                this.RaisePropertyChanged("precioDocena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double precioMayor {
            get {
                return this.precioMayorField;
            }
            set {
                this.precioMayorField = value;
                this.RaisePropertyChanged("precioMayor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double precioUnidad {
            get {
                return this.precioUnidadField;
            }
            set {
                this.precioUnidadField = value;
                this.RaisePropertyChanged("precioUnidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("promociones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public promocion[] promociones {
            get {
                return this.promocionesField;
            }
            set {
                this.promocionesField = value;
                this.RaisePropertyChanged("promociones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int stockPrenda {
            get {
                return this.stockPrendaField;
            }
            set {
                this.stockPrendaField = value;
                this.RaisePropertyChanged("stockPrenda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("talla", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public System.Nullable<talla>[] talla {
            get {
                return this.tallaField;
            }
            set {
                this.tallaField = value;
                this.RaisePropertyChanged("talla");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public abstract partial class descuento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool esAutomaticoField;
        
        private int idDescuentoField;
        
        private string nombreField;
        
        private vigencia vigenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool esAutomatico {
            get {
                return this.esAutomaticoField;
            }
            set {
                this.esAutomaticoField = value;
                this.RaisePropertyChanged("esAutomatico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idDescuento {
            get {
                return this.idDescuentoField;
            }
            set {
                this.idDescuentoField = value;
                this.RaisePropertyChanged("idDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public vigencia vigencia {
            get {
                return this.vigenciaField;
            }
            set {
                this.vigenciaField = value;
                this.RaisePropertyChanged("vigencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public partial class vigencia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idVigenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idVigencia {
            get {
                return this.idVigenciaField;
            }
            set {
                this.idVigenciaField = value;
                this.RaisePropertyChanged("idVigencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public abstract partial class promocion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool esAutomaticoField;
        
        private int idPromocionField;
        
        private string nombreField;
        
        private vigencia vigenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool esAutomatico {
            get {
                return this.esAutomaticoField;
            }
            set {
                this.esAutomaticoField = value;
                this.RaisePropertyChanged("esAutomatico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idPromocion {
            get {
                return this.idPromocionField;
            }
            set {
                this.idPromocionField = value;
                this.RaisePropertyChanged("idPromocion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public vigencia vigencia {
            get {
                return this.vigenciaField;
            }
            set {
                this.vigenciaField = value;
                this.RaisePropertyChanged("vigencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public partial class almacen : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idField;
        
        private int idTiendaField;
        
        private string nombreField;
        
        private int stockField;
        
        private string ubicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idTienda {
            get {
                return this.idTiendaField;
            }
            set {
                this.idTiendaField = value;
                this.RaisePropertyChanged("idTienda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public partial class lote : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private almacen datAlmacenField;
        
        private string descripcionField;
        
        private int idLoteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public almacen datAlmacen {
            get {
                return this.datAlmacenField;
            }
            set {
                this.datAlmacenField = value;
                this.RaisePropertyChanged("datAlmacen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idLote {
            get {
                return this.idLoteField;
            }
            set {
                this.idLoteField = value;
                this.RaisePropertyChanged("idLote");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public enum material {
        
        /// <remarks/>
        Algodon,
        
        /// <remarks/>
        Poliester,
        
        /// <remarks/>
        algodon_poliester,
        
        /// <remarks/>
        Lino,
        
        /// <remarks/>
        Rayon,
        
        /// <remarks/>
        Lana,
        
        /// <remarks/>
        Acrilico,
        
        /// <remarks/>
        Nylon,
        
        /// <remarks/>
        lycra,
        
        /// <remarks/>
        Denim,
        
        /// <remarks/>
        Drill,
        
        /// <remarks/>
        Gabardina,
        
        /// <remarks/>
        Polar,
        
        /// <remarks/>
        Franela,
        
        /// <remarks/>
        Cuero,
        
        /// <remarks/>
        Cuerina,
        
        /// <remarks/>
        Saten,
        
        /// <remarks/>
        Chifon,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public enum talla {
        
        /// <remarks/>
        XS,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        XL,
        
        /// <remarks/>
        XXL,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="filtrarGorros", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class filtrarGorrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreLike;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string colorLike;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string materialLike;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoGorraLike;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool tallaAjustable;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool impermeable;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double precioMin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double precioMax;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool soloActivos;
        
        public filtrarGorrosRequest() {
        }
        
        public filtrarGorrosRequest(string nombreLike, string colorLike, string materialLike, string tipoGorraLike, bool tallaAjustable, bool impermeable, double precioMin, double precioMax, bool soloActivos) {
            this.nombreLike = nombreLike;
            this.colorLike = colorLike;
            this.materialLike = materialLike;
            this.tipoGorraLike = tipoGorraLike;
            this.tallaAjustable = tallaAjustable;
            this.impermeable = impermeable;
            this.precioMin = precioMin;
            this.precioMax = precioMax;
            this.soloActivos = soloActivos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="filtrarGorrosResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class filtrarGorrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.GorroWS.gorro[] @return;
        
        public filtrarGorrosResponse() {
        }
        
        public filtrarGorrosResponse(WearDropWA.GorroWS.gorro[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarGorro", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarGorroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.GorroWS.gorro gorro;
        
        public insertarGorroRequest() {
        }
        
        public insertarGorroRequest(WearDropWA.GorroWS.gorro gorro) {
            this.gorro = gorro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarGorroResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarGorroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarGorroResponse() {
        }
        
        public insertarGorroResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerGorroPorId", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerGorroPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idGorro;
        
        public obtenerGorroPorIdRequest() {
        }
        
        public obtenerGorroPorIdRequest(int idGorro) {
            this.idGorro = idGorro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerGorroPorIdResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerGorroPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.GorroWS.gorro @return;
        
        public obtenerGorroPorIdResponse() {
        }
        
        public obtenerGorroPorIdResponse(WearDropWA.GorroWS.gorro @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarGorro", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarGorroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.GorroWS.gorro gorro;
        
        public modificarGorroRequest() {
        }
        
        public modificarGorroRequest(WearDropWA.GorroWS.gorro gorro) {
            this.gorro = gorro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarGorroResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarGorroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarGorroResponse() {
        }
        
        public modificarGorroResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarGorros", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarGorrosRequest {
        
        public listarGorrosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarGorrosResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarGorrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.GorroWS.gorro[] @return;
        
        public listarGorrosResponse() {
        }
        
        public listarGorrosResponse(WearDropWA.GorroWS.gorro[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GorroWSChannel : WearDropWA.GorroWS.GorroWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GorroWSClient : System.ServiceModel.ClientBase<WearDropWA.GorroWS.GorroWS>, WearDropWA.GorroWS.GorroWS {
        
        public GorroWSClient() {
        }
        
        public GorroWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GorroWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GorroWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GorroWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.GorroWS.eliminarGorroResponse WearDropWA.GorroWS.GorroWS.eliminarGorro(WearDropWA.GorroWS.eliminarGorroRequest request) {
            return base.Channel.eliminarGorro(request);
        }
        
        public int eliminarGorro(int idGorro) {
            WearDropWA.GorroWS.eliminarGorroRequest inValue = new WearDropWA.GorroWS.eliminarGorroRequest();
            inValue.idGorro = idGorro;
            WearDropWA.GorroWS.eliminarGorroResponse retVal = ((WearDropWA.GorroWS.GorroWS)(this)).eliminarGorro(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.GorroWS.eliminarGorroResponse> WearDropWA.GorroWS.GorroWS.eliminarGorroAsync(WearDropWA.GorroWS.eliminarGorroRequest request) {
            return base.Channel.eliminarGorroAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.GorroWS.eliminarGorroResponse> eliminarGorroAsync(int idGorro) {
            WearDropWA.GorroWS.eliminarGorroRequest inValue = new WearDropWA.GorroWS.eliminarGorroRequest();
            inValue.idGorro = idGorro;
            return ((WearDropWA.GorroWS.GorroWS)(this)).eliminarGorroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.GorroWS.filtrarGorrosResponse WearDropWA.GorroWS.GorroWS.filtrarGorros(WearDropWA.GorroWS.filtrarGorrosRequest request) {
            return base.Channel.filtrarGorros(request);
        }
        
        public WearDropWA.GorroWS.gorro[] filtrarGorros(string nombreLike, string colorLike, string materialLike, string tipoGorraLike, bool tallaAjustable, bool impermeable, double precioMin, double precioMax, bool soloActivos) {
            WearDropWA.GorroWS.filtrarGorrosRequest inValue = new WearDropWA.GorroWS.filtrarGorrosRequest();
            inValue.nombreLike = nombreLike;
            inValue.colorLike = colorLike;
            inValue.materialLike = materialLike;
            inValue.tipoGorraLike = tipoGorraLike;
            inValue.tallaAjustable = tallaAjustable;
            inValue.impermeable = impermeable;
            inValue.precioMin = precioMin;
            inValue.precioMax = precioMax;
            inValue.soloActivos = soloActivos;
            WearDropWA.GorroWS.filtrarGorrosResponse retVal = ((WearDropWA.GorroWS.GorroWS)(this)).filtrarGorros(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.GorroWS.filtrarGorrosResponse> WearDropWA.GorroWS.GorroWS.filtrarGorrosAsync(WearDropWA.GorroWS.filtrarGorrosRequest request) {
            return base.Channel.filtrarGorrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.GorroWS.filtrarGorrosResponse> filtrarGorrosAsync(string nombreLike, string colorLike, string materialLike, string tipoGorraLike, bool tallaAjustable, bool impermeable, double precioMin, double precioMax, bool soloActivos) {
            WearDropWA.GorroWS.filtrarGorrosRequest inValue = new WearDropWA.GorroWS.filtrarGorrosRequest();
            inValue.nombreLike = nombreLike;
            inValue.colorLike = colorLike;
            inValue.materialLike = materialLike;
            inValue.tipoGorraLike = tipoGorraLike;
            inValue.tallaAjustable = tallaAjustable;
            inValue.impermeable = impermeable;
            inValue.precioMin = precioMin;
            inValue.precioMax = precioMax;
            inValue.soloActivos = soloActivos;
            return ((WearDropWA.GorroWS.GorroWS)(this)).filtrarGorrosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.GorroWS.insertarGorroResponse WearDropWA.GorroWS.GorroWS.insertarGorro(WearDropWA.GorroWS.insertarGorroRequest request) {
            return base.Channel.insertarGorro(request);
        }
        
        public int insertarGorro(WearDropWA.GorroWS.gorro gorro) {
            WearDropWA.GorroWS.insertarGorroRequest inValue = new WearDropWA.GorroWS.insertarGorroRequest();
            inValue.gorro = gorro;
            WearDropWA.GorroWS.insertarGorroResponse retVal = ((WearDropWA.GorroWS.GorroWS)(this)).insertarGorro(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.GorroWS.insertarGorroResponse> WearDropWA.GorroWS.GorroWS.insertarGorroAsync(WearDropWA.GorroWS.insertarGorroRequest request) {
            return base.Channel.insertarGorroAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.GorroWS.insertarGorroResponse> insertarGorroAsync(WearDropWA.GorroWS.gorro gorro) {
            WearDropWA.GorroWS.insertarGorroRequest inValue = new WearDropWA.GorroWS.insertarGorroRequest();
            inValue.gorro = gorro;
            return ((WearDropWA.GorroWS.GorroWS)(this)).insertarGorroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.GorroWS.obtenerGorroPorIdResponse WearDropWA.GorroWS.GorroWS.obtenerGorroPorId(WearDropWA.GorroWS.obtenerGorroPorIdRequest request) {
            return base.Channel.obtenerGorroPorId(request);
        }
        
        public WearDropWA.GorroWS.gorro obtenerGorroPorId(int idGorro) {
            WearDropWA.GorroWS.obtenerGorroPorIdRequest inValue = new WearDropWA.GorroWS.obtenerGorroPorIdRequest();
            inValue.idGorro = idGorro;
            WearDropWA.GorroWS.obtenerGorroPorIdResponse retVal = ((WearDropWA.GorroWS.GorroWS)(this)).obtenerGorroPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.GorroWS.obtenerGorroPorIdResponse> WearDropWA.GorroWS.GorroWS.obtenerGorroPorIdAsync(WearDropWA.GorroWS.obtenerGorroPorIdRequest request) {
            return base.Channel.obtenerGorroPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.GorroWS.obtenerGorroPorIdResponse> obtenerGorroPorIdAsync(int idGorro) {
            WearDropWA.GorroWS.obtenerGorroPorIdRequest inValue = new WearDropWA.GorroWS.obtenerGorroPorIdRequest();
            inValue.idGorro = idGorro;
            return ((WearDropWA.GorroWS.GorroWS)(this)).obtenerGorroPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.GorroWS.modificarGorroResponse WearDropWA.GorroWS.GorroWS.modificarGorro(WearDropWA.GorroWS.modificarGorroRequest request) {
            return base.Channel.modificarGorro(request);
        }
        
        public int modificarGorro(WearDropWA.GorroWS.gorro gorro) {
            WearDropWA.GorroWS.modificarGorroRequest inValue = new WearDropWA.GorroWS.modificarGorroRequest();
            inValue.gorro = gorro;
            WearDropWA.GorroWS.modificarGorroResponse retVal = ((WearDropWA.GorroWS.GorroWS)(this)).modificarGorro(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.GorroWS.modificarGorroResponse> WearDropWA.GorroWS.GorroWS.modificarGorroAsync(WearDropWA.GorroWS.modificarGorroRequest request) {
            return base.Channel.modificarGorroAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.GorroWS.modificarGorroResponse> modificarGorroAsync(WearDropWA.GorroWS.gorro gorro) {
            WearDropWA.GorroWS.modificarGorroRequest inValue = new WearDropWA.GorroWS.modificarGorroRequest();
            inValue.gorro = gorro;
            return ((WearDropWA.GorroWS.GorroWS)(this)).modificarGorroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.GorroWS.listarGorrosResponse WearDropWA.GorroWS.GorroWS.listarGorros(WearDropWA.GorroWS.listarGorrosRequest request) {
            return base.Channel.listarGorros(request);
        }
        
        public WearDropWA.GorroWS.gorro[] listarGorros() {
            WearDropWA.GorroWS.listarGorrosRequest inValue = new WearDropWA.GorroWS.listarGorrosRequest();
            WearDropWA.GorroWS.listarGorrosResponse retVal = ((WearDropWA.GorroWS.GorroWS)(this)).listarGorros(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.GorroWS.listarGorrosResponse> WearDropWA.GorroWS.GorroWS.listarGorrosAsync(WearDropWA.GorroWS.listarGorrosRequest request) {
            return base.Channel.listarGorrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.GorroWS.listarGorrosResponse> listarGorrosAsync() {
            WearDropWA.GorroWS.listarGorrosRequest inValue = new WearDropWA.GorroWS.listarGorrosRequest();
            return ((WearDropWA.GorroWS.GorroWS)(this)).listarGorrosAsync(inValue);
        }
    }
}
