//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WearDropWA.VigenciaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://vigencia.services.weardrop.pucp.edu.pe/", ConfigurationName="VigenciaWS.VigenciaWS")]
    public interface VigenciaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/helloRequest", ReplyAction="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.VigenciaWS.helloResponse hello(WearDropWA.VigenciaWS.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/helloRequest", ReplyAction="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/helloResponse")]
        System.Threading.Tasks.Task<WearDropWA.VigenciaWS.helloResponse> helloAsync(WearDropWA.VigenciaWS.helloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/mosrtra_vigenciasRequest" +
            "", ReplyAction="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/mosrtra_vigenciasRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.VigenciaWS.mosrtra_vigenciasResponse mosrtra_vigencias(WearDropWA.VigenciaWS.mosrtra_vigenciasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/mosrtra_vigenciasRequest" +
            "", ReplyAction="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/mosrtra_vigenciasRespons" +
            "e")]
        System.Threading.Tasks.Task<WearDropWA.VigenciaWS.mosrtra_vigenciasResponse> mosrtra_vigenciasAsync(WearDropWA.VigenciaWS.mosrtra_vigenciasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/obtenerPorIdRequest", ReplyAction="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/obtenerPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.VigenciaWS.obtenerPorIdResponse obtenerPorId(WearDropWA.VigenciaWS.obtenerPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/obtenerPorIdRequest", ReplyAction="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/obtenerPorIdResponse")]
        System.Threading.Tasks.Task<WearDropWA.VigenciaWS.obtenerPorIdResponse> obtenerPorIdAsync(WearDropWA.VigenciaWS.obtenerPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/eliminarVigenciaRequest", ReplyAction="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/eliminarVigenciaResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.VigenciaWS.eliminarVigenciaResponse eliminarVigencia(WearDropWA.VigenciaWS.eliminarVigenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/eliminarVigenciaRequest", ReplyAction="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/eliminarVigenciaResponse" +
            "")]
        System.Threading.Tasks.Task<WearDropWA.VigenciaWS.eliminarVigenciaResponse> eliminarVigenciaAsync(WearDropWA.VigenciaWS.eliminarVigenciaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/modificarVigenciaRequest" +
            "", ReplyAction="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/modificarVigenciaRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.VigenciaWS.modificarVigenciaResponse modificarVigencia(WearDropWA.VigenciaWS.modificarVigenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/modificarVigenciaRequest" +
            "", ReplyAction="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/modificarVigenciaRespons" +
            "e")]
        System.Threading.Tasks.Task<WearDropWA.VigenciaWS.modificarVigenciaResponse> modificarVigenciaAsync(WearDropWA.VigenciaWS.modificarVigenciaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/mostrar_vigenciasActivas" +
            "Request", ReplyAction="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/mostrar_vigenciasActivas" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.VigenciaWS.mostrar_vigenciasActivasResponse mostrar_vigenciasActivas(WearDropWA.VigenciaWS.mostrar_vigenciasActivasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/mostrar_vigenciasActivas" +
            "Request", ReplyAction="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/mostrar_vigenciasActivas" +
            "Response")]
        System.Threading.Tasks.Task<WearDropWA.VigenciaWS.mostrar_vigenciasActivasResponse> mostrar_vigenciasActivasAsync(WearDropWA.VigenciaWS.mostrar_vigenciasActivasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/insertarVigenciaRequest", ReplyAction="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/insertarVigenciaResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.VigenciaWS.insertarVigenciaResponse insertarVigencia(WearDropWA.VigenciaWS.insertarVigenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/insertarVigenciaRequest", ReplyAction="http://vigencia.services.weardrop.pucp.edu.pe/VigenciaWS/insertarVigenciaResponse" +
            "")]
        System.Threading.Tasks.Task<WearDropWA.VigenciaWS.insertarVigenciaResponse> insertarVigenciaAsync(WearDropWA.VigenciaWS.insertarVigenciaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://vigencia.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vigencia.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://vigencia.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vigencia.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vigencia.services.weardrop.pucp.edu.pe/")]
    public partial class vigencia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idVigenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idVigencia {
            get {
                return this.idVigenciaField;
            }
            set {
                this.idVigenciaField = value;
                this.RaisePropertyChanged("idVigencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mosrtra_vigencias", WrapperNamespace="http://vigencia.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class mosrtra_vigenciasRequest {
        
        public mosrtra_vigenciasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mosrtra_vigenciasResponse", WrapperNamespace="http://vigencia.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class mosrtra_vigenciasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vigencia.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.VigenciaWS.vigencia[] @return;
        
        public mosrtra_vigenciasResponse() {
        }
        
        public mosrtra_vigenciasResponse(WearDropWA.VigenciaWS.vigencia[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorId", WrapperNamespace="http://vigencia.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vigencia.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDesc;
        
        public obtenerPorIdRequest() {
        }
        
        public obtenerPorIdRequest(int idDesc) {
            this.idDesc = idDesc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdResponse", WrapperNamespace="http://vigencia.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vigencia.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.VigenciaWS.vigencia @return;
        
        public obtenerPorIdResponse() {
        }
        
        public obtenerPorIdResponse(WearDropWA.VigenciaWS.vigencia @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarVigencia", WrapperNamespace="http://vigencia.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarVigenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vigencia.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDesc;
        
        public eliminarVigenciaRequest() {
        }
        
        public eliminarVigenciaRequest(int idDesc) {
            this.idDesc = idDesc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarVigenciaResponse", WrapperNamespace="http://vigencia.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarVigenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vigencia.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarVigenciaResponse() {
        }
        
        public eliminarVigenciaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarVigencia", WrapperNamespace="http://vigencia.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarVigenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vigencia.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.VigenciaWS.vigencia datDesc;
        
        public modificarVigenciaRequest() {
        }
        
        public modificarVigenciaRequest(WearDropWA.VigenciaWS.vigencia datDesc) {
            this.datDesc = datDesc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarVigenciaResponse", WrapperNamespace="http://vigencia.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarVigenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vigencia.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarVigenciaResponse() {
        }
        
        public modificarVigenciaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mostrar_vigenciasActivas", WrapperNamespace="http://vigencia.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class mostrar_vigenciasActivasRequest {
        
        public mostrar_vigenciasActivasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mostrar_vigenciasActivasResponse", WrapperNamespace="http://vigencia.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class mostrar_vigenciasActivasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vigencia.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.VigenciaWS.vigencia[] @return;
        
        public mostrar_vigenciasActivasResponse() {
        }
        
        public mostrar_vigenciasActivasResponse(WearDropWA.VigenciaWS.vigencia[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarVigencia", WrapperNamespace="http://vigencia.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarVigenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vigencia.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.VigenciaWS.vigencia datDesc;
        
        public insertarVigenciaRequest() {
        }
        
        public insertarVigenciaRequest(WearDropWA.VigenciaWS.vigencia datDesc) {
            this.datDesc = datDesc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarVigenciaResponse", WrapperNamespace="http://vigencia.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarVigenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vigencia.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarVigenciaResponse() {
        }
        
        public insertarVigenciaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VigenciaWSChannel : WearDropWA.VigenciaWS.VigenciaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VigenciaWSClient : System.ServiceModel.ClientBase<WearDropWA.VigenciaWS.VigenciaWS>, WearDropWA.VigenciaWS.VigenciaWS {
        
        public VigenciaWSClient() {
        }
        
        public VigenciaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VigenciaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VigenciaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VigenciaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.VigenciaWS.helloResponse WearDropWA.VigenciaWS.VigenciaWS.hello(WearDropWA.VigenciaWS.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            WearDropWA.VigenciaWS.helloRequest inValue = new WearDropWA.VigenciaWS.helloRequest();
            inValue.name = name;
            WearDropWA.VigenciaWS.helloResponse retVal = ((WearDropWA.VigenciaWS.VigenciaWS)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.VigenciaWS.helloResponse> WearDropWA.VigenciaWS.VigenciaWS.helloAsync(WearDropWA.VigenciaWS.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.VigenciaWS.helloResponse> helloAsync(string name) {
            WearDropWA.VigenciaWS.helloRequest inValue = new WearDropWA.VigenciaWS.helloRequest();
            inValue.name = name;
            return ((WearDropWA.VigenciaWS.VigenciaWS)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.VigenciaWS.mosrtra_vigenciasResponse WearDropWA.VigenciaWS.VigenciaWS.mosrtra_vigencias(WearDropWA.VigenciaWS.mosrtra_vigenciasRequest request) {
            return base.Channel.mosrtra_vigencias(request);
        }
        
        public WearDropWA.VigenciaWS.vigencia[] mosrtra_vigencias() {
            WearDropWA.VigenciaWS.mosrtra_vigenciasRequest inValue = new WearDropWA.VigenciaWS.mosrtra_vigenciasRequest();
            WearDropWA.VigenciaWS.mosrtra_vigenciasResponse retVal = ((WearDropWA.VigenciaWS.VigenciaWS)(this)).mosrtra_vigencias(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.VigenciaWS.mosrtra_vigenciasResponse> WearDropWA.VigenciaWS.VigenciaWS.mosrtra_vigenciasAsync(WearDropWA.VigenciaWS.mosrtra_vigenciasRequest request) {
            return base.Channel.mosrtra_vigenciasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.VigenciaWS.mosrtra_vigenciasResponse> mosrtra_vigenciasAsync() {
            WearDropWA.VigenciaWS.mosrtra_vigenciasRequest inValue = new WearDropWA.VigenciaWS.mosrtra_vigenciasRequest();
            return ((WearDropWA.VigenciaWS.VigenciaWS)(this)).mosrtra_vigenciasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.VigenciaWS.obtenerPorIdResponse WearDropWA.VigenciaWS.VigenciaWS.obtenerPorId(WearDropWA.VigenciaWS.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorId(request);
        }
        
        public WearDropWA.VigenciaWS.vigencia obtenerPorId(int idDesc) {
            WearDropWA.VigenciaWS.obtenerPorIdRequest inValue = new WearDropWA.VigenciaWS.obtenerPorIdRequest();
            inValue.idDesc = idDesc;
            WearDropWA.VigenciaWS.obtenerPorIdResponse retVal = ((WearDropWA.VigenciaWS.VigenciaWS)(this)).obtenerPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.VigenciaWS.obtenerPorIdResponse> WearDropWA.VigenciaWS.VigenciaWS.obtenerPorIdAsync(WearDropWA.VigenciaWS.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.VigenciaWS.obtenerPorIdResponse> obtenerPorIdAsync(int idDesc) {
            WearDropWA.VigenciaWS.obtenerPorIdRequest inValue = new WearDropWA.VigenciaWS.obtenerPorIdRequest();
            inValue.idDesc = idDesc;
            return ((WearDropWA.VigenciaWS.VigenciaWS)(this)).obtenerPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.VigenciaWS.eliminarVigenciaResponse WearDropWA.VigenciaWS.VigenciaWS.eliminarVigencia(WearDropWA.VigenciaWS.eliminarVigenciaRequest request) {
            return base.Channel.eliminarVigencia(request);
        }
        
        public int eliminarVigencia(int idDesc) {
            WearDropWA.VigenciaWS.eliminarVigenciaRequest inValue = new WearDropWA.VigenciaWS.eliminarVigenciaRequest();
            inValue.idDesc = idDesc;
            WearDropWA.VigenciaWS.eliminarVigenciaResponse retVal = ((WearDropWA.VigenciaWS.VigenciaWS)(this)).eliminarVigencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.VigenciaWS.eliminarVigenciaResponse> WearDropWA.VigenciaWS.VigenciaWS.eliminarVigenciaAsync(WearDropWA.VigenciaWS.eliminarVigenciaRequest request) {
            return base.Channel.eliminarVigenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.VigenciaWS.eliminarVigenciaResponse> eliminarVigenciaAsync(int idDesc) {
            WearDropWA.VigenciaWS.eliminarVigenciaRequest inValue = new WearDropWA.VigenciaWS.eliminarVigenciaRequest();
            inValue.idDesc = idDesc;
            return ((WearDropWA.VigenciaWS.VigenciaWS)(this)).eliminarVigenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.VigenciaWS.modificarVigenciaResponse WearDropWA.VigenciaWS.VigenciaWS.modificarVigencia(WearDropWA.VigenciaWS.modificarVigenciaRequest request) {
            return base.Channel.modificarVigencia(request);
        }
        
        public int modificarVigencia(WearDropWA.VigenciaWS.vigencia datDesc) {
            WearDropWA.VigenciaWS.modificarVigenciaRequest inValue = new WearDropWA.VigenciaWS.modificarVigenciaRequest();
            inValue.datDesc = datDesc;
            WearDropWA.VigenciaWS.modificarVigenciaResponse retVal = ((WearDropWA.VigenciaWS.VigenciaWS)(this)).modificarVigencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.VigenciaWS.modificarVigenciaResponse> WearDropWA.VigenciaWS.VigenciaWS.modificarVigenciaAsync(WearDropWA.VigenciaWS.modificarVigenciaRequest request) {
            return base.Channel.modificarVigenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.VigenciaWS.modificarVigenciaResponse> modificarVigenciaAsync(WearDropWA.VigenciaWS.vigencia datDesc) {
            WearDropWA.VigenciaWS.modificarVigenciaRequest inValue = new WearDropWA.VigenciaWS.modificarVigenciaRequest();
            inValue.datDesc = datDesc;
            return ((WearDropWA.VigenciaWS.VigenciaWS)(this)).modificarVigenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.VigenciaWS.mostrar_vigenciasActivasResponse WearDropWA.VigenciaWS.VigenciaWS.mostrar_vigenciasActivas(WearDropWA.VigenciaWS.mostrar_vigenciasActivasRequest request) {
            return base.Channel.mostrar_vigenciasActivas(request);
        }
        
        public WearDropWA.VigenciaWS.vigencia[] mostrar_vigenciasActivas() {
            WearDropWA.VigenciaWS.mostrar_vigenciasActivasRequest inValue = new WearDropWA.VigenciaWS.mostrar_vigenciasActivasRequest();
            WearDropWA.VigenciaWS.mostrar_vigenciasActivasResponse retVal = ((WearDropWA.VigenciaWS.VigenciaWS)(this)).mostrar_vigenciasActivas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.VigenciaWS.mostrar_vigenciasActivasResponse> WearDropWA.VigenciaWS.VigenciaWS.mostrar_vigenciasActivasAsync(WearDropWA.VigenciaWS.mostrar_vigenciasActivasRequest request) {
            return base.Channel.mostrar_vigenciasActivasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.VigenciaWS.mostrar_vigenciasActivasResponse> mostrar_vigenciasActivasAsync() {
            WearDropWA.VigenciaWS.mostrar_vigenciasActivasRequest inValue = new WearDropWA.VigenciaWS.mostrar_vigenciasActivasRequest();
            return ((WearDropWA.VigenciaWS.VigenciaWS)(this)).mostrar_vigenciasActivasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.VigenciaWS.insertarVigenciaResponse WearDropWA.VigenciaWS.VigenciaWS.insertarVigencia(WearDropWA.VigenciaWS.insertarVigenciaRequest request) {
            return base.Channel.insertarVigencia(request);
        }
        
        public int insertarVigencia(WearDropWA.VigenciaWS.vigencia datDesc) {
            WearDropWA.VigenciaWS.insertarVigenciaRequest inValue = new WearDropWA.VigenciaWS.insertarVigenciaRequest();
            inValue.datDesc = datDesc;
            WearDropWA.VigenciaWS.insertarVigenciaResponse retVal = ((WearDropWA.VigenciaWS.VigenciaWS)(this)).insertarVigencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.VigenciaWS.insertarVigenciaResponse> WearDropWA.VigenciaWS.VigenciaWS.insertarVigenciaAsync(WearDropWA.VigenciaWS.insertarVigenciaRequest request) {
            return base.Channel.insertarVigenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.VigenciaWS.insertarVigenciaResponse> insertarVigenciaAsync(WearDropWA.VigenciaWS.vigencia datDesc) {
            WearDropWA.VigenciaWS.insertarVigenciaRequest inValue = new WearDropWA.VigenciaWS.insertarVigenciaRequest();
            inValue.datDesc = datDesc;
            return ((WearDropWA.VigenciaWS.VigenciaWS)(this)).insertarVigenciaAsync(inValue);
        }
    }
}
