//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WearDropWA.BlusaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", ConfigurationName="BlusaWS.BlusaWS")]
    public interface BlusaWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/filtrarBlusasRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/filtrarBlusasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(prenda))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.BlusaWS.filtrarBlusasResponse filtrarBlusas(WearDropWA.BlusaWS.filtrarBlusasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/filtrarBlusasRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/filtrarBlusasResponse")]
        System.Threading.Tasks.Task<WearDropWA.BlusaWS.filtrarBlusasResponse> filtrarBlusasAsync(WearDropWA.BlusaWS.filtrarBlusasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/insertarBlusaRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/insertarBlusaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(prenda))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.BlusaWS.insertarBlusaResponse insertarBlusa(WearDropWA.BlusaWS.insertarBlusaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/insertarBlusaRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/insertarBlusaResponse")]
        System.Threading.Tasks.Task<WearDropWA.BlusaWS.insertarBlusaResponse> insertarBlusaAsync(WearDropWA.BlusaWS.insertarBlusaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/modificarBlusaRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/modificarBlusaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(prenda))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.BlusaWS.modificarBlusaResponse modificarBlusa(WearDropWA.BlusaWS.modificarBlusaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/modificarBlusaRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/modificarBlusaResponse")]
        System.Threading.Tasks.Task<WearDropWA.BlusaWS.modificarBlusaResponse> modificarBlusaAsync(WearDropWA.BlusaWS.modificarBlusaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/eliminarBlusaRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/eliminarBlusaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(prenda))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.BlusaWS.eliminarBlusaResponse eliminarBlusa(WearDropWA.BlusaWS.eliminarBlusaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/eliminarBlusaRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/eliminarBlusaResponse")]
        System.Threading.Tasks.Task<WearDropWA.BlusaWS.eliminarBlusaResponse> eliminarBlusaAsync(WearDropWA.BlusaWS.eliminarBlusaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/obtenerBlusaPorIdRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/obtenerBlusaPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(prenda))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.BlusaWS.obtenerBlusaPorIdResponse obtenerBlusaPorId(WearDropWA.BlusaWS.obtenerBlusaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/obtenerBlusaPorIdRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/obtenerBlusaPorIdResponse")]
        System.Threading.Tasks.Task<WearDropWA.BlusaWS.obtenerBlusaPorIdResponse> obtenerBlusaPorIdAsync(WearDropWA.BlusaWS.obtenerBlusaPorIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/listarBlusasRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/listarBlusasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(prenda))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WearDropWA.BlusaWS.listarBlusasResponse listarBlusas(WearDropWA.BlusaWS.listarBlusasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/listarBlusasRequest", ReplyAction="http://prendas.services.weardrop.pucp.edu.pe/BlusaWS/listarBlusasResponse")]
        System.Threading.Tasks.Task<WearDropWA.BlusaWS.listarBlusasResponse> listarBlusasAsync(WearDropWA.BlusaWS.listarBlusasRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public partial class blusa : prenda {
        
        private tipoBlusa tipoBlusaField;
        
        private bool tipoBlusaFieldSpecified;
        
        private tipoManga tipoMangaField;
        
        private bool tipoMangaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public tipoBlusa tipoBlusa {
            get {
                return this.tipoBlusaField;
            }
            set {
                this.tipoBlusaField = value;
                this.RaisePropertyChanged("tipoBlusa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoBlusaSpecified {
            get {
                return this.tipoBlusaFieldSpecified;
            }
            set {
                this.tipoBlusaFieldSpecified = value;
                this.RaisePropertyChanged("tipoBlusaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public tipoManga tipoManga {
            get {
                return this.tipoMangaField;
            }
            set {
                this.tipoMangaField = value;
                this.RaisePropertyChanged("tipoManga");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoMangaSpecified {
            get {
                return this.tipoMangaFieldSpecified;
            }
            set {
                this.tipoMangaFieldSpecified = value;
                this.RaisePropertyChanged("tipoMangaSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public enum tipoBlusa {
        
        /// <remarks/>
        Camisera,
        
        /// <remarks/>
        CropTop,
        
        /// <remarks/>
        Peplum,
        
        /// <remarks/>
        OffShoulder,
        
        /// <remarks/>
        Transparente,
        
        /// <remarks/>
        Formal,
        
        /// <remarks/>
        Casual,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public enum tipoManga {
        
        /// <remarks/>
        MangaCorta,
        
        /// <remarks/>
        MangaLarga,
        
        /// <remarks/>
        SinManga,
        
        /// <remarks/>
        Globo,
        
        /// <remarks/>
        Campana,
        
        /// <remarks/>
        TresCuartos,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(blusa))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public abstract partial class prenda : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int alertaMinStockField;
        
        private string colorField;
        
        private descuento[] descuentosField;
        
        private int idPrendaField;
        
        private lote[] lotesField;
        
        private material materialField;
        
        private bool materialFieldSpecified;
        
        private string nombreField;
        
        private double precioDocenaField;
        
        private double precioMayorField;
        
        private double precioUnidadField;
        
        private promocion[] promocionesField;
        
        private int stockPrendaField;
        
        private System.Nullable<talla>[] tallaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int alertaMinStock {
            get {
                return this.alertaMinStockField;
            }
            set {
                this.alertaMinStockField = value;
                this.RaisePropertyChanged("alertaMinStock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("color");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("descuentos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public descuento[] descuentos {
            get {
                return this.descuentosField;
            }
            set {
                this.descuentosField = value;
                this.RaisePropertyChanged("descuentos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idPrenda {
            get {
                return this.idPrendaField;
            }
            set {
                this.idPrendaField = value;
                this.RaisePropertyChanged("idPrenda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lotes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public lote[] lotes {
            get {
                return this.lotesField;
            }
            set {
                this.lotesField = value;
                this.RaisePropertyChanged("lotes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public material material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
                this.RaisePropertyChanged("material");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool materialSpecified {
            get {
                return this.materialFieldSpecified;
            }
            set {
                this.materialFieldSpecified = value;
                this.RaisePropertyChanged("materialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double precioDocena {
            get {
                return this.precioDocenaField;
            }
            set {
                this.precioDocenaField = value;
                this.RaisePropertyChanged("precioDocena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double precioMayor {
            get {
                return this.precioMayorField;
            }
            set {
                this.precioMayorField = value;
                this.RaisePropertyChanged("precioMayor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double precioUnidad {
            get {
                return this.precioUnidadField;
            }
            set {
                this.precioUnidadField = value;
                this.RaisePropertyChanged("precioUnidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("promociones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public promocion[] promociones {
            get {
                return this.promocionesField;
            }
            set {
                this.promocionesField = value;
                this.RaisePropertyChanged("promociones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int stockPrenda {
            get {
                return this.stockPrendaField;
            }
            set {
                this.stockPrendaField = value;
                this.RaisePropertyChanged("stockPrenda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("talla", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public System.Nullable<talla>[] talla {
            get {
                return this.tallaField;
            }
            set {
                this.tallaField = value;
                this.RaisePropertyChanged("talla");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public abstract partial class descuento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool esAutomaticoField;
        
        private int idDescuentoField;
        
        private string nombreField;
        
        private vigencia vigenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool esAutomatico {
            get {
                return this.esAutomaticoField;
            }
            set {
                this.esAutomaticoField = value;
                this.RaisePropertyChanged("esAutomatico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idDescuento {
            get {
                return this.idDescuentoField;
            }
            set {
                this.idDescuentoField = value;
                this.RaisePropertyChanged("idDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public vigencia vigencia {
            get {
                return this.vigenciaField;
            }
            set {
                this.vigenciaField = value;
                this.RaisePropertyChanged("vigencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public partial class vigencia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idVigenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idVigencia {
            get {
                return this.idVigenciaField;
            }
            set {
                this.idVigenciaField = value;
                this.RaisePropertyChanged("idVigencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public abstract partial class promocion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool esAutomaticoField;
        
        private int idPromocionField;
        
        private string nombreField;
        
        private vigencia vigenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool esAutomatico {
            get {
                return this.esAutomaticoField;
            }
            set {
                this.esAutomaticoField = value;
                this.RaisePropertyChanged("esAutomatico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idPromocion {
            get {
                return this.idPromocionField;
            }
            set {
                this.idPromocionField = value;
                this.RaisePropertyChanged("idPromocion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public vigencia vigencia {
            get {
                return this.vigenciaField;
            }
            set {
                this.vigenciaField = value;
                this.RaisePropertyChanged("vigencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public partial class almacen : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idField;
        
        private int idTiendaField;
        
        private string nombreField;
        
        private int stockField;
        
        private string ubicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idTienda {
            get {
                return this.idTiendaField;
            }
            set {
                this.idTiendaField = value;
                this.RaisePropertyChanged("idTienda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public partial class lote : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private almacen datAlmacenField;
        
        private string descripcionField;
        
        private int idLoteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public almacen datAlmacen {
            get {
                return this.datAlmacenField;
            }
            set {
                this.datAlmacenField = value;
                this.RaisePropertyChanged("datAlmacen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idLote {
            get {
                return this.idLoteField;
            }
            set {
                this.idLoteField = value;
                this.RaisePropertyChanged("idLote");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public enum material {
        
        /// <remarks/>
        Algodon,
        
        /// <remarks/>
        Poliester,
        
        /// <remarks/>
        algodon_poliester,
        
        /// <remarks/>
        Lino,
        
        /// <remarks/>
        Rayon,
        
        /// <remarks/>
        Lana,
        
        /// <remarks/>
        Acrilico,
        
        /// <remarks/>
        Nylon,
        
        /// <remarks/>
        lycra,
        
        /// <remarks/>
        Denim,
        
        /// <remarks/>
        Drill,
        
        /// <remarks/>
        Gabardina,
        
        /// <remarks/>
        Polar,
        
        /// <remarks/>
        Franela,
        
        /// <remarks/>
        Cuero,
        
        /// <remarks/>
        Cuerina,
        
        /// <remarks/>
        Saten,
        
        /// <remarks/>
        Chifon,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/")]
    public enum talla {
        
        /// <remarks/>
        XS,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        XL,
        
        /// <remarks/>
        XXL,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="filtrarBlusas", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class filtrarBlusasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreLike;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string colorLike;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string materialLike;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoBlusaLike;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoMangaLike;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double precioMin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double precioMax;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool soloActivos;
        
        public filtrarBlusasRequest() {
        }
        
        public filtrarBlusasRequest(string nombreLike, string colorLike, string materialLike, string tipoBlusaLike, string tipoMangaLike, double precioMin, double precioMax, bool soloActivos) {
            this.nombreLike = nombreLike;
            this.colorLike = colorLike;
            this.materialLike = materialLike;
            this.tipoBlusaLike = tipoBlusaLike;
            this.tipoMangaLike = tipoMangaLike;
            this.precioMin = precioMin;
            this.precioMax = precioMax;
            this.soloActivos = soloActivos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="filtrarBlusasResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class filtrarBlusasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.BlusaWS.blusa[] @return;
        
        public filtrarBlusasResponse() {
        }
        
        public filtrarBlusasResponse(WearDropWA.BlusaWS.blusa[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarBlusa", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarBlusaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.BlusaWS.blusa blusa;
        
        public insertarBlusaRequest() {
        }
        
        public insertarBlusaRequest(WearDropWA.BlusaWS.blusa blusa) {
            this.blusa = blusa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarBlusaResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarBlusaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarBlusaResponse() {
        }
        
        public insertarBlusaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarBlusa", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarBlusaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.BlusaWS.blusa blusa;
        
        public modificarBlusaRequest() {
        }
        
        public modificarBlusaRequest(WearDropWA.BlusaWS.blusa blusa) {
            this.blusa = blusa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarBlusaResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarBlusaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarBlusaResponse() {
        }
        
        public modificarBlusaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarBlusa", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarBlusaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idBlusa;
        
        public eliminarBlusaRequest() {
        }
        
        public eliminarBlusaRequest(int idBlusa) {
            this.idBlusa = idBlusa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarBlusaResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarBlusaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarBlusaResponse() {
        }
        
        public eliminarBlusaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerBlusaPorId", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerBlusaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idBlusa;
        
        public obtenerBlusaPorIdRequest() {
        }
        
        public obtenerBlusaPorIdRequest(int idBlusa) {
            this.idBlusa = idBlusa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerBlusaPorIdResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerBlusaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.BlusaWS.blusa @return;
        
        public obtenerBlusaPorIdResponse() {
        }
        
        public obtenerBlusaPorIdResponse(WearDropWA.BlusaWS.blusa @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarBlusas", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarBlusasRequest {
        
        public listarBlusasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarBlusasResponse", WrapperNamespace="http://prendas.services.weardrop.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarBlusasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prendas.services.weardrop.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WearDropWA.BlusaWS.blusa[] @return;
        
        public listarBlusasResponse() {
        }
        
        public listarBlusasResponse(WearDropWA.BlusaWS.blusa[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BlusaWSChannel : WearDropWA.BlusaWS.BlusaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BlusaWSClient : System.ServiceModel.ClientBase<WearDropWA.BlusaWS.BlusaWS>, WearDropWA.BlusaWS.BlusaWS {
        
        public BlusaWSClient() {
        }
        
        public BlusaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BlusaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlusaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlusaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.BlusaWS.filtrarBlusasResponse WearDropWA.BlusaWS.BlusaWS.filtrarBlusas(WearDropWA.BlusaWS.filtrarBlusasRequest request) {
            return base.Channel.filtrarBlusas(request);
        }
        
        public WearDropWA.BlusaWS.blusa[] filtrarBlusas(string nombreLike, string colorLike, string materialLike, string tipoBlusaLike, string tipoMangaLike, double precioMin, double precioMax, bool soloActivos) {
            WearDropWA.BlusaWS.filtrarBlusasRequest inValue = new WearDropWA.BlusaWS.filtrarBlusasRequest();
            inValue.nombreLike = nombreLike;
            inValue.colorLike = colorLike;
            inValue.materialLike = materialLike;
            inValue.tipoBlusaLike = tipoBlusaLike;
            inValue.tipoMangaLike = tipoMangaLike;
            inValue.precioMin = precioMin;
            inValue.precioMax = precioMax;
            inValue.soloActivos = soloActivos;
            WearDropWA.BlusaWS.filtrarBlusasResponse retVal = ((WearDropWA.BlusaWS.BlusaWS)(this)).filtrarBlusas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.BlusaWS.filtrarBlusasResponse> WearDropWA.BlusaWS.BlusaWS.filtrarBlusasAsync(WearDropWA.BlusaWS.filtrarBlusasRequest request) {
            return base.Channel.filtrarBlusasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.BlusaWS.filtrarBlusasResponse> filtrarBlusasAsync(string nombreLike, string colorLike, string materialLike, string tipoBlusaLike, string tipoMangaLike, double precioMin, double precioMax, bool soloActivos) {
            WearDropWA.BlusaWS.filtrarBlusasRequest inValue = new WearDropWA.BlusaWS.filtrarBlusasRequest();
            inValue.nombreLike = nombreLike;
            inValue.colorLike = colorLike;
            inValue.materialLike = materialLike;
            inValue.tipoBlusaLike = tipoBlusaLike;
            inValue.tipoMangaLike = tipoMangaLike;
            inValue.precioMin = precioMin;
            inValue.precioMax = precioMax;
            inValue.soloActivos = soloActivos;
            return ((WearDropWA.BlusaWS.BlusaWS)(this)).filtrarBlusasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.BlusaWS.insertarBlusaResponse WearDropWA.BlusaWS.BlusaWS.insertarBlusa(WearDropWA.BlusaWS.insertarBlusaRequest request) {
            return base.Channel.insertarBlusa(request);
        }
        
        public int insertarBlusa(WearDropWA.BlusaWS.blusa blusa) {
            WearDropWA.BlusaWS.insertarBlusaRequest inValue = new WearDropWA.BlusaWS.insertarBlusaRequest();
            inValue.blusa = blusa;
            WearDropWA.BlusaWS.insertarBlusaResponse retVal = ((WearDropWA.BlusaWS.BlusaWS)(this)).insertarBlusa(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.BlusaWS.insertarBlusaResponse> WearDropWA.BlusaWS.BlusaWS.insertarBlusaAsync(WearDropWA.BlusaWS.insertarBlusaRequest request) {
            return base.Channel.insertarBlusaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.BlusaWS.insertarBlusaResponse> insertarBlusaAsync(WearDropWA.BlusaWS.blusa blusa) {
            WearDropWA.BlusaWS.insertarBlusaRequest inValue = new WearDropWA.BlusaWS.insertarBlusaRequest();
            inValue.blusa = blusa;
            return ((WearDropWA.BlusaWS.BlusaWS)(this)).insertarBlusaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.BlusaWS.modificarBlusaResponse WearDropWA.BlusaWS.BlusaWS.modificarBlusa(WearDropWA.BlusaWS.modificarBlusaRequest request) {
            return base.Channel.modificarBlusa(request);
        }
        
        public int modificarBlusa(WearDropWA.BlusaWS.blusa blusa) {
            WearDropWA.BlusaWS.modificarBlusaRequest inValue = new WearDropWA.BlusaWS.modificarBlusaRequest();
            inValue.blusa = blusa;
            WearDropWA.BlusaWS.modificarBlusaResponse retVal = ((WearDropWA.BlusaWS.BlusaWS)(this)).modificarBlusa(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.BlusaWS.modificarBlusaResponse> WearDropWA.BlusaWS.BlusaWS.modificarBlusaAsync(WearDropWA.BlusaWS.modificarBlusaRequest request) {
            return base.Channel.modificarBlusaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.BlusaWS.modificarBlusaResponse> modificarBlusaAsync(WearDropWA.BlusaWS.blusa blusa) {
            WearDropWA.BlusaWS.modificarBlusaRequest inValue = new WearDropWA.BlusaWS.modificarBlusaRequest();
            inValue.blusa = blusa;
            return ((WearDropWA.BlusaWS.BlusaWS)(this)).modificarBlusaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.BlusaWS.eliminarBlusaResponse WearDropWA.BlusaWS.BlusaWS.eliminarBlusa(WearDropWA.BlusaWS.eliminarBlusaRequest request) {
            return base.Channel.eliminarBlusa(request);
        }
        
        public int eliminarBlusa(int idBlusa) {
            WearDropWA.BlusaWS.eliminarBlusaRequest inValue = new WearDropWA.BlusaWS.eliminarBlusaRequest();
            inValue.idBlusa = idBlusa;
            WearDropWA.BlusaWS.eliminarBlusaResponse retVal = ((WearDropWA.BlusaWS.BlusaWS)(this)).eliminarBlusa(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.BlusaWS.eliminarBlusaResponse> WearDropWA.BlusaWS.BlusaWS.eliminarBlusaAsync(WearDropWA.BlusaWS.eliminarBlusaRequest request) {
            return base.Channel.eliminarBlusaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.BlusaWS.eliminarBlusaResponse> eliminarBlusaAsync(int idBlusa) {
            WearDropWA.BlusaWS.eliminarBlusaRequest inValue = new WearDropWA.BlusaWS.eliminarBlusaRequest();
            inValue.idBlusa = idBlusa;
            return ((WearDropWA.BlusaWS.BlusaWS)(this)).eliminarBlusaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.BlusaWS.obtenerBlusaPorIdResponse WearDropWA.BlusaWS.BlusaWS.obtenerBlusaPorId(WearDropWA.BlusaWS.obtenerBlusaPorIdRequest request) {
            return base.Channel.obtenerBlusaPorId(request);
        }
        
        public WearDropWA.BlusaWS.blusa obtenerBlusaPorId(int idBlusa) {
            WearDropWA.BlusaWS.obtenerBlusaPorIdRequest inValue = new WearDropWA.BlusaWS.obtenerBlusaPorIdRequest();
            inValue.idBlusa = idBlusa;
            WearDropWA.BlusaWS.obtenerBlusaPorIdResponse retVal = ((WearDropWA.BlusaWS.BlusaWS)(this)).obtenerBlusaPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.BlusaWS.obtenerBlusaPorIdResponse> WearDropWA.BlusaWS.BlusaWS.obtenerBlusaPorIdAsync(WearDropWA.BlusaWS.obtenerBlusaPorIdRequest request) {
            return base.Channel.obtenerBlusaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.BlusaWS.obtenerBlusaPorIdResponse> obtenerBlusaPorIdAsync(int idBlusa) {
            WearDropWA.BlusaWS.obtenerBlusaPorIdRequest inValue = new WearDropWA.BlusaWS.obtenerBlusaPorIdRequest();
            inValue.idBlusa = idBlusa;
            return ((WearDropWA.BlusaWS.BlusaWS)(this)).obtenerBlusaPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WearDropWA.BlusaWS.listarBlusasResponse WearDropWA.BlusaWS.BlusaWS.listarBlusas(WearDropWA.BlusaWS.listarBlusasRequest request) {
            return base.Channel.listarBlusas(request);
        }
        
        public WearDropWA.BlusaWS.blusa[] listarBlusas() {
            WearDropWA.BlusaWS.listarBlusasRequest inValue = new WearDropWA.BlusaWS.listarBlusasRequest();
            WearDropWA.BlusaWS.listarBlusasResponse retVal = ((WearDropWA.BlusaWS.BlusaWS)(this)).listarBlusas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WearDropWA.BlusaWS.listarBlusasResponse> WearDropWA.BlusaWS.BlusaWS.listarBlusasAsync(WearDropWA.BlusaWS.listarBlusasRequest request) {
            return base.Channel.listarBlusasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WearDropWA.BlusaWS.listarBlusasResponse> listarBlusasAsync() {
            WearDropWA.BlusaWS.listarBlusasRequest inValue = new WearDropWA.BlusaWS.listarBlusasRequest();
            return ((WearDropWA.BlusaWS.BlusaWS)(this)).listarBlusasAsync(inValue);
        }
    }
}
